### ISSUE TITLE
iCal error if SIP or H.323 not found in invite

### ISSUE THREAD

**Issue by nstefanski** [jrchamp/moodle-mod_zoom#270]
As mentioned in #193, if SIP or H.323 information are not found in the invite, and debugging messages are turned on, then the iCal download fails. This should generally only affect development environments when the institution's Zoom meeting plan does not include SIP or H.323, but can be recreated with the following steps:

1. In Site administration -> Development -> Debugging, set "Debug messages" to "DEVELOPER"
2. In Site administration -> Plugins -> Activity modules -> Zoom, set "SIP pattern" and/or "H.323 message pattern" to blank
3. Create a new Zoom meeting activity
4. Log in as a student or switch role to student and view the Zoom meeting activity
5. Click the "Download iCal" button and attempt to save the .ics file

Presumably this could be resolved by adding admin settings for whether SIP and H.323 are expected to be found in the meeting invite.

**Comment by jrchamp** [comment]
This is an area, where I think that "blank" might be a valid opportunity to skip the check. add_paragraph_break_above_element() has some code that does this and I think it would be reasonable to add it to remove_element() as well. @andrewmadden and @abias Would your use case still be viable? Other thoughts?

**Comment by abias** [comment]
> Would your use case still be viable? Other thoughts?

@jrchamp , I have commented in #274.
