### ISSUE TITLE
Choose an specific Zoom user account

### ISSUE THREAD

**Issue by celiaorix** [jrchamp/moodle-mod_zoom#278]
We have a Pro Zoom account and 7 licensed user accounts.

We create a Zoom meeting in Moodle but we can not choose the licensed user account we want to be the host. We only can create the Zoom meeting with the main pro account.

Is it possible to choose another "child account"?

Thanks!

**Comment by jrchamp** [comment]
When you create a Zoom meeting through Moodle, by default, it creates the meeting for the current Moodle user.

To create a meeting for another user, you have two options:

1. Use the "Schedule for" functionality: https://support.zoom.us/hc/en-us/articles/201362803-Scheduling-privilege
2. Log in as the other Moodle user and create the Zoom meeting.

Either way, to create the meeting for the other user directly from Moodle, the other users will need to have access to create Zoom meetings in the Moodle course.

**Comment by jrchamp** [comment]
Hopefully this answered your question. For now, I will mark it as closed. If you have a followup, please let us know. Thank you!
