### ISSUE TITLE
Add the possibility to record a meeting at creation time

### ISSUE THREAD

**Issue by lcollong** [jrchamp/moodle-mod_zoom#281]
Enhancement : When creating a new meeting, have the checkbox to select the option to activate the recording of the meeting.
It corresponds to the API POST/Create a meeting/Settings object/auto_recording which could have three values (none, cloud, local).
This is not related to the ability to read or get a meeting's record within Moodle.

**Comment by jrchamp** [comment]
Hi @lcollong

I agree that the functionality has value to users who like automatic recording. It is worth nothing that there are some concerns about extraneous recordings (when people join early, on the wrong day), malicious recordings (when uninvited users join) and privacy (the recording begins immediately when joining without an opportunity for consent). As such, this functionality is not something that is a high priority for me, but we are open to accepting a pull request with these changes.

A couple things for someone who plans to develop this functionality:
 - Not all enterprise accounts have Cloud Recording available.
 - Not all users have access to Cloud Recording, even if it is available to the enterprise account.
 - The Moodle administrator may want to limit if these options are available. The two possible ways of implementing this are Moodle's capabilities and plugin configuration options.

**Comment by lcollong** [comment]
Hi @jrchamp ,

Thanks for your comments. As a way of simplify the idea, we'd appreciate any feedback about the default setup in zoom. Our hosts have their profile parameters set to default record meeting in the cloud. So each new meeting created in the Zoom UI is set to record by default without having to manually set it. However, meetings created from within Moodle using the API are set to "no recording" whatever are the general parameters. Is this the case for other users ? Would it be possible to get the default value from the API and set the meeting according to so while creating a new one? Without any choices in Moodle itself to avoid the considerations you are pointing.

**Comment by jrchamp** [comment]
https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usersettings appears to provide the user's meeting settings, which should allow us to use them to supplement the API call when creating a meeting.

**Comment by lcollong** [comment]
Good news. Thanks for taking time to check.

**Comment by aduranterres** [comment]
Hi @jrchamp 

I am helping @lcollong with this.
I just submitted a pull request. Please let me know if you think I should make any changes.

I have a doubt: 
If you set configuration to allow changing auto-recording option on meeting creation, and you set up a meeting on behalf of another user, the dropdown with the available recording options should reload, fetching the selected user configuration from Zoom. However, I don't know if Moodle provides a way to do this in the activity settings page, and I could not find any info about this, so please let me know if you have any insights.

**Comment by aduranterres** [comment]
After posting I found some info about my doubt. It seems I should use definition_after_data function for that, so I will look into it and see if I can make it work.

**Comment by jrchamp** [comment]
Hi @aduranterres! I had an idea that may help address your doubt. What if the default value for record was to use the user default constant? The option would be "User Default". Then we wouldn't need to display the default value for the individual user or worry about changing the value based on the schedule_for value.

**Comment by aduranterres** [comment]
Hi @jrchamp! Sorry for the delay on this. First it took me a while to get going, as I had not worked much with Moodle forms before, especially the Javascript part. Then, summer holidays did not help.

Thanks for your suggestion, but I think I got it working as I wanted now. I implemented definition_after_data and the needed javascript to make it change when you change the schedule_for value.
I was waiting for @lcollong to provide a proper testing environment, as I don't have a Zoom account with several users I can use to verify my changes are really working as expected.
I have updated my PR now, hopefully I did not break anything in the process...well it seems I did, of course. The tests are not passing, and I don't know why. If you have any comments, please let me know.

A quick recap: 
- If showschedulingprivilege is disabled, nothing changes
- If it is enabled: the new JS code will make the form reload when you change the schedule_for value, to get the Zoom settings for that user and show the correct values in the Auto recording option.

While writing this I noticed that I have a mistake: all the form reload code should only run if showschedulingprivilege AND allowrecordingchangeoption are enabled. So, I should modify it, as now it will reload even if allowrecordingchangeoption is disabled, which does not make sense.

Please let me know your thoughts and if you think I should do something differently.
Thank you!

**Comment by aduranterres** [comment]
I found the issue, I hadn't noticed the error about the missing documentation on the new function, so now the tests are passing....well not so fast. I see 2 are passing and the rest are not. But this is a new problem, related to the new Javascript file.
I have no idea why 2 tests pass and the rest don't, so please let me know if you have any comments. I could try running grunt again, but I don't really know what I am doing there, so I prefer to wait for your input.

**Comment by jrchamp** [comment]
Right now, grunt needs to be run with Moodle 3.9 (current LTS), 3.10 or 3.11. Unfortunately Moodle 4.0 grunt output doesn't match anything else. When Moodle 4.1 (upcoming LTS) is released, we'll switch our files and tests to match that grunt output.

Overall, I would like to minimize the amount of custom JavaScript. I don't want to take away from the work that you did, but I think the maintainability will be better if the code is smaller.

I think that if it's a basic select list, with User Default as the initial option, then we get the same functionality without needing to reload the form or add JavaScript. Example:
```
<select>
  <option value="default" selected="selected">User Default</option>
  <option value="none">Manual Recording</option>
  <option value="local">Automatic Local Recording</option>
  <option value="cloud">Automatic Cloud Recording</option>
</select>
```

**Comment by aduranterres** [comment]
Thanks for the info about grunt.

Also, thanks for your comments. Of course, it is up to you to decide how you want this to work, so I'll adapt, and I think it would be good enough for @lcollong so it should be fine. I also prefer to stay away from Javascript if I can :)

That said, I don't think that would provide the same functionality:
 - If I schedule a meeting for you, the plugin would set "Automatic recording" to "User default", but I would be able to change that value.
 - If, for example, you have only Local recording enabled in your account, but when setting up the meeting I change the value to Cloud, I would think that the meeting would be recorded to the cloud, when that really can't happen because you don't have it enabled.

With the code I submitted, when you change the user you schedule for, it will get that user settings, and only show the really available options in the "Automatic recording" field.

Thank you!

**Comment by jrchamp** [comment]
@aduranterres Good point! Out of curiosity, does the Zoom API throw an error when an invalid recording option is selected?

When the form reloads because the schedule_for user changes, does it keep the in-progress changes or are they lost? We'll need to verify this during testing, but I wasn't sure if you already knew the answer.

**Comment by aduranterres** [comment]
> does the Zoom API throw an error when an invalid recording option is selected?

No, it seems it just creates the meeting with no auto-recording set. I just tested it disabling local recording for my user, and creating a meeting with auto-recording=local. It was created with no auto-recording.

> When the form reloads because the schedule_for user changes, does it keep the in-progress changes or are they lost?

They are kept.

**Comment by aduranterres** [comment]
I have finally being able to test the form reload with users with different recording permissions, and everything seems to be working fine: on form reload after changing the value of " Schedule meeting for", the correct values appear on the "Auto recording" selector, according to the selected user privileges.
