### ISSUE TITLE
Reset not implemented

### ISSUE THREAD

**Issue by izendegi** [jrchamp/moodle-mod_zoom#287]
When resetting a Moodle course that has a Zoom activity the page shows a message telling that this activity hasn't implemented that feature.

**Comment by jrchamp** [comment]
Thank you for reporting this. I did some quick searching and this appears to be Moodle's documentation regarding a module's implementation of the Reset course functionality: https://docs.moodle.org/dev/Implementing_Reset_course_functionality_in_a_module

**Comment by izendegi** [comment]
Yes, it seems that the plugin has to describe those functions to support the course reset functionality (even if it doesn't reset data at all)
