### ISSUE TITLE
Emoji in meeting description get lost

### ISSUE THREAD

**Issue by yanus** [jrchamp/moodle-mod_zoom#289]
[also see [https://moodle.org/mod/forum/discuss.php?d=425347](https://moodle.org/mod/forum/discuss.php?d=425347)]
I want to use emoji in meeting descriptions (e.g. country flags to indicate different time zones). Everything works fine, until the meetings are updated through the `\mod_zoom\task\update_meetings` scheduled task which replaces the emoji with hyphens:
`=> Field "intro" has changed from "<p dir="ltr" style="text-align: left;"><strong>Introduction</strong></p><p dir="ltr" style="text-align: left;">�&nbsp;17 janvier 2022</p><p dir="ltr" style="text-align: left;">��&nbsp;09:00-11:00</p><p dir="ltr" style="text-align: left;">��&nbsp;10:00-12:00<br></p>" to "<p dir="ltr" style="text-align: left;"><strong>Introduction</strong></p><p dir="ltr" style="text-align: left;">-&nbsp;17 janvier 2022</p><p dir="ltr" style="text-align: left;">--&nbsp;09:00-11:00</p><p dir="ltr" style="text-align: left;">--&nbsp;10:00-12:00<br></p>"`
Apparently Zoom doesn't support emoji in the meeting description and thus they are lost when reading it back from Zoom.
Workaround could be to disable the scheduled task (as long as you don't need to change the meeting information outside of Moodle).
A better solution might be to offer an option not to sync the description with Zoom in the first place (it seems a bit problematic anyway, as Zoom doesn't support any HTML formatting which Moodle inserts by default).

**Comment by jrchamp** [comment]
Related #190 and #196

Personally, I'm leaning towards only pushing the Moodle description to Zoom (after passing through `content_to_text()` so that the Zoom side is slightly more friendly than the previous strip_tags and the current HTML mess). Syncing it back from Zoom doesn't seem very helpful.
