### ISSUE TITLE
Ability to edit a zoom event that is in the past

### ISSUE THREAD

**Issue by davefoord** [jrchamp/moodle-mod_zoom#297]
It would be good to be able to edit the description of a zoom meeting that is in the past? On one of my projects, we record the meetings, and then share this back with the users - the easiest way for me to do this, is to simply add a link to the recording back into the description of the item, so it keeps everything in one place - however it won't allow me to save the item, as it recognises that the meeting is scheduled in the past.

**Comment by jrchamp** [comment]
Thanks @davefoord! I want to make sure that there is no ambiguity for whomever works on this, so please let me know if my understanding is not complete.

Problem: Within Moodle, if a Zoom activity is "in the past", it is not possible to edit the Moodle activity's description.

**Comment by davefoord** [comment]
Yes - your understanding is correct. If the activity is in the past, you cannot edit any of the items within it (including the description) as it won't let you save the changes.

**Comment by jrchamp** [comment]
That makes a lot of sense now why it's happening. Here's the relevant code: https://github.com/ncstate-delta/moodle-mod_zoom/blob/5515dccbe15e9c1cefb7b378b2a70c435bbd6f3d/mod_form.php#L646-L648

So the purpose of the current logic is to avoid the situation where a user attempts to create a *new* activity with a start_date that is in the past.

Options to adjust the logic may include:
 - if this activity already exists, then skip the "creating a new activity" checks
 - or more strictly: if the activity exists and the values have not changed, skip each "new activity" check

**Comment by tlock** [comment]
This looks like a simple patch to mod_form.php:

-            if ($data['start_time'] < time()) {
+            if ($data['start_time'] < time() && $data['meeting_id'] < 0) {
