### ISSUE TITLE
Class 'mod_zoom\invitation' not found

### ISSUE THREAD

**Issue by jrchamp** [jrchamp/moodle-mod_zoom#298]
A user reported:
```
Excepción - Class 'mod_zoom\invitation' not found
```

There are two places where the class is used:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/5515dccbe15e9c1cefb7b378b2a70c435bbd6f3d/settings.php#L325-L331
https://github.com/ncstate-delta/moodle-mod_zoom/blob/5515dccbe15e9c1cefb7b378b2a70c435bbd6f3d/classes/webservice.php#L690-L699

@andrewmadden I don't see where the class gets explicitly included anywhere. Is it included implicitly? Is there a situation, like upgrade, where the class file might not be included implicitly and should instead be included explicitly?

**Comment by byvamo** [comment]
Thanks @jrchamp, how can I know when the problem has been solved?

**Comment by jrchamp** [comment]
The line that I think is the one that should directly fix the issue you are seeing is:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/0b08aaeaf71878c2be247f9fb9378dca1fca97c2/settings.php#L33

You would put that line into the file right after this line:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/5515dccbe15e9c1cefb7b378b2a70c435bbd6f3d/settings.php#L32

The file should then look like this:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/0b08aaeaf71878c2be247f9fb9378dca1fca97c2/settings.php#L31-L35

**Comment by byvamo** [comment]
Thanks @jrchamp Which file should I edit?

**Comment by byvamo** [comment]
Hello, I already made the change, I will be testing and I will inform you how it behaves, thanks @jrchamp

**Comment by jrchamp** [comment]
First, some background information:
 - A Zoom user can be either Basic or Licensed.
 - A Basic Zoom user who is hosting a group Meeting (more than 2 people) is limited to 40 minutes.
 - A Licensed Zoom user can host a group Meeting and are not limited to 40 minutes.
 - The Webinar feature is a different license that costs additional money and can only be added to Licensed Zoom users.
 - Webinar licenses come in multiple sizes like Webinar 500, Webinar 1000 and more.

If you have a user `account@example.com` in your Zoom "account" who is Licensed and has been assigned a Webinar 500 license, then in Moodle, if that user has a Moodle account with the email address set to `account@example.com`, they should have the ability to create Webinars.

**Comment by byvamo** [comment]
Perfect, I understand that, so there is no part in the plugin where you can configure that regardless of the user's email, always create meetings or webinars with the account that has the zoom license?

**Comment by jrchamp** [comment]
You are correct that there isn't a place in the configuration to always create meetings/webinars using a single account. Typically, that's not what you want anyway, because a user can only Host a single meeting or webinar at a time.

**Comment by jrchamp** [comment]
Oh right, did the fix work for you? Can you access the plugin settings and Site Administration pages without error now?

**Comment by byvamo** [comment]
You rock !, It no longer generates the error when I enter the administration of the site or the configuration of the Plugin, thank you very much for helping me. Thanks @jrchamp
