### ISSUE TITLE
Moodle and Zoom disconnected

### ISSUE THREAD

**Issue by ShilVita** [jrchamp/moodle-mod_zoom#313]
@jrchamp  Hi, please a need your help!

I can't login through Moodle after a while and it asks me to join again through ZOOM. It seems to have disconnected. How can I solve it?
Apparently it has something to do with the API token.

Thanks a lot!

Syl.

**Comment by jrchamp** [comment]
Sorry, I don't fully understand which problem you are describing. The only connection in this plugin between Moodle and Zoom is the JWT API token. If there is a problem with it, no one would be unable to create or edit any Zoom activities.

I'm not sure what you mean by "join again". If you mean "log in" to your Zoom account, that's separate from this plugin. Zoom wants meeting hosts to log in directly to their accounts using the Zoom client. Moodle does not act as a Zoom login proxy.

If you have screenshots or a recording of the issue you are experiencing, please share and I'll be happy to take a look.

**Comment by ShilVita** [comment]
Thanks for your answer !

I send video about the problem: https://youtu.be/chMsmDWzIrQ
The green button to log in works for approximately 2 hours, after that it does not work.

1. The version of our moodle is 3.10.4
2. The version of the zoom extension is 4.1.1.
3. We work with educational zoom licenses

When we had the version of the extension 3.4 the disconnection problem appeared sporadically, when updating to 4.1.1 all sessions of all accounts were generalized.

We have tested in 2 different Moodle with versions 3.10.4 and 3.11 and it does not work.
We have installed zoom pro licenses and it does not work.

**The connection link says**: https://us06web.zoom.us/s/85288260862?zak=eyJ0eXAiOiJKV1QiLCJzdiI6IjAwMDAwMSIsInptX3NrbSI6InptX28ybSIsImFsZyI6IkhTMjU2In0.eyJhdWQiOiJjbGllbnRzbSIsInVpZCI6Imo1UElrOWFmVEhDR05PZW4zbHJZWlEiLCJpc3MiOiJ3ZWIiLCJzdHkiOjEwMCwid2NkIjoidXMwNiIsImNsdCI6MCwibW51bSI6Ijg1Mjg4MjYwODYyIiwic3RrIjoiRmNVRFY3dm42WUxUdGZadnhtVDB3Tng4WWZIbGxPZjBFU3RLZ2M3Qi00TS5CZ1k0TVdKdlRVeHpPRnBJYm04eFVtMVNlSEJuTm5KaVZrNTFhVW8wVGxKbFZqZEJUbWs0T0UxRVV5OUJNa0Z0WWxGNGFUQnpZa2RSUFQxQU16a3laak0xTjJRMFpEbGhNV1UzTm1ZeE1URm1NRE0xTm1NM1lqTmxNamxqTlROaFpETmlORFV5TW1RMU56RmtNakF4TldVeVltVXpOVFptWWpkak1BQWdUbGR2VGtOMVowcE1aMjFHZDNKV2IyaHhjalpMYUVWTFZsbzJMMDB6UlRJQUJIVnpNRFlBQUFGOFhTU185Z0FTZFFBQUFBIiwiZXhwIjoxNjMzNjU3NDYyLCJpYXQiOjE2MzM2NTAyNjIsImFpZCI6Im5LYVpTS0NrUXZ1SGc1VzJMUGRvVVEiLCJjaWQiOiIifQ.uF5dyRRCkwnP637zou9qDfb9T-WXSfPLOag41u5q5x4

We don't know how to solve the problem.


Please help us!

Thanks a lot!

Syl.

**Comment by jrchamp** [comment]
If the link is working for a couple hours and then it stops working, that's probably the `start_url` because it does expire. Have you tried logging in to Zoom first? https://zoom.us/signin

You may also want to check the Zoom account settings:
Specifically, you may want to choose "Allow participants to join before host" and "Require a passcode when scheduling new meetings"

**Comment by ShilVita** [comment]
We think it is also because of the star_url, how can we correct it?

When we login via zoom.us before moodle, the session can be opened. The problem is that for security reasons we do not allow the hosts to enter the account from zoom.us. Moodle gave us the security of entering only through Moodle but with this problem we cannot open a session directly from Moodle.

**Comment by ShilVita** [comment]
Dear Chistopher.

We made all the recommended changes and we have recovered the connection, it works perfectly.

Thank you very much for all your support.

Greetings!

**Comment by jrchamp** [comment]
Thank you @ShilVita! That's great news. After some internal testing, we should be able to merge the code and release a new version that contains the fix.
