### ISSUE TITLE
Sessions report returning no data for most of the Zoom sessions but not all of them

### ISSUE THREAD

**Issue by celoxgroup** [jrchamp/moodle-mod_zoom#317]
Hi Team,

I have strange behaviour on Zoom module version 4.1.1 (2021090200), If I do create a new Zoom link and run few sessions the Session report returning no data. If I do check on scheduled tasks I am getting the following error.

`Execute scheduled task: Get meeting report from Zoom (mod_zoom\task\get_meeting_reports)
... started 06:00:02. Current memory use 21.7MB.
Finding meetings between 2021-10-10T13:00:02Z to 2021-10-10T19:00:02Z
Using Dashboard API
Zoom received a bad request: This API is only available for Business or higher accounts that have enabled the Dashboard feature.
Using Reports API
Empty hostuuids, querying all hosts
Processing 0 active host uuids
Processing 0 meetings
... used 3 dbqueries
... used 2.0733668804169 seconds
Scheduled task complete: Get meeting report from Zoom (mod_zoom\task\get_meeting_reports)`

Zoom account overview: Currently using 9 PRO licensed accounts. 
Moodle version: 3.9 (20200615)

I would understand that I need a Business or Enterprise level account but for some Zoom links the session report does work.

**Comment by jrchamp** [comment]
It's not that a Business account is required. The code tries to use the Dashboard API for performance reasons. If it fails, it falls back to the Reports API. https://github.com/ncstate-delta/moodle-mod_zoom/blob/09b465a654b3f80e78879c5592efbfe89e9f4c75/classes/task/get_meeting_reports.php#L143-L155

So in your case, it should be using these Reports API calls:
 - https://marketplace.zoom.us/docs/api-reference/zoom-api/reports/reportusers
 - https://marketplace.zoom.us/docs/api-reference/zoom-api/reports/reportmeetings

However, it looks like the response says that "0 active host uuids" were found. Is it possible that some of the meetings were 1 user only? Alternatively, it may mean that the active host report is not 100% reliable in the moment (there may be a delay).

As you have a list of 9 users, it may be best to try and pass in that list to the task via the `cli/get_meeting_report.php` script. It looks like the current code only works for one user at a time, but it would not be difficult to make it work with a comma separated list.

**Comment by celoxgroup** [comment]
Thank you @jrchamp, I executed the CLI and check the UUID for all licensed users in the database and the data were still missing, Anyway after checking the **get_meeting_report.php** I saw that the script return only 1 day worth of recordings but luckily the CLI script accept date range which fixed the issue!

The reports are back after execution of the following script with additional parameters **/mod/zoom/cli/get_meeting_report.php --start=2021-10-01  --end=2021-10-12**

Once again thank you! Case closed
