### ISSUE TITLE
Timeline - Events not get removed

### ISSUE THREAD

**Issue by martinoesterreicher** [jrchamp/moodle-mod_zoom#318]
Zoom Meeting Event entries are not getting deleted from the moodle timeline block.
1. Create a Zoom Meeting as recurring meeting with recurrence being "no fixed time". Then there wont be any entries made to the timeline block, which is fine.
2. Set Recurrence to weekly e.g. Monday 10:00 ending a few months in the future. Then then timeline block will list those weekly meetings.
3. Set Recurrence back to "no fixed time" and the previously listed meetings are still shown in the timeline block, which is wrong.
4. Deleting the meeting will remove all entries regarding that meeting from the timeline block.

It seems as if the zoom moodle plugin doesnt propagate the events correctly to the timeline block.

**Comment by martinoesterreicher** [comment]
I have to ask and wait for a colleague todo the updates on the plugin, but I think we should be able to test this.

**Comment by martinoesterreicher** [comment]
We tried the codechange and it still behaves the same way.

**Comment by jrchamp** [comment]
Yes, it looks like the we're on track to release a new version with this fix included two days from now. Thank you for confirming it was working for you.
