### ISSUE TITLE
Zoom meeting sync scheduled task is inefficient

### ISSUE THREAD

**Issue by deraadt** [jrchamp/moodle-mod_zoom#321]
We noted that the Zoom meeting sync scheduled task was lasting for about 400 seconds, which is probably a product of how many Zoom activities we have.

As it runs for ~8min every 30min, this consumes a lot of time used by cron. I doubt it's creating huge load during this, but it is causing other cron jobs to back up.

As a workaround, we've reduced the syncing to daily and early in the morning. We assume users are more likely to edit the meeting in Moodle if they've created it there.

**Comment by jrchamp** [comment]
As background, to frame the discussion, here's the default update_meetings task schedule that @deraadt is referencing:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/d1b667a6c09d3a2dc94959c56648bdc90da9992a/db/tasks.php#L28-L36

Philosophically, assuming that users are less likely to gain any benefit from this task makes a lot of sense. These are meetings created from Moodle and for Moodle, so Moodle should be the primary source of truth.

Overall, the update_meetings task does two things:

1. Marks expired sessions as expired (a form of automatic cleanup, which I like).
2. Synchronizes changes made externally (which is potentially beneficial, when Moodle is out of sync with Zoom).

I'm not sure how many of the changes in Zoom we care a lot about, but the timeliness of that synchronization probably does not need to be hourly. Daily, early morning make a lot of sense from my perspective (4:30 a.m. perhaps?).

Anyone have concerns, questions or other suggestions?
