### ISSUE TITLE
Zoom webinar unavailable

### ISSUE THREAD

**Issue by dottbarbieri** [jrchamp/moodle-mod_zoom#322]
Hi,
I can't understand why the webinar option is always grayed and unavailable. 
My Zoom subscription include the Webinar&Event plan, as I perform Zoom webinar in-platform on a regular basis.
In Moodle I can create a new Zoom meeting, but it seems "I am not preauthorized" to create webinar... so does anyone know what's the trick?

Thanks,
Giacomo

**Comment by jrchamp** [comment]
Do you know if `Webinar&Event` is a single license? If it's `Webinar` + `Event`, then I would imagine that the code would be fine, but it's possible that the Event license is formatted differently and the code doesn't know to test it.

**Comment by jrchamp** [comment]
@dottbarbieri I've opened #338 to hopefully address this issue. If you can test that set of changes to confirm that it resolves the issue, that would help move this forward.

**Comment by jrchamp** [comment]
Hi @dottbarbieri - In case you are able to test the proposed changes, that would make it possible for us to merge the code.
