### ISSUE TITLE
When changing a zoom activity's title on the course main page with quick edit, recurring meetings get corrupted

### ISSUE THREAD

**Issue by alina-kiz** [jrchamp/moodle-mod_zoom#324]
Hi,
we have noticed a problem with the recurring meetings feature which has been integrated recently into this plugin:
When changing a zoom activity's title on the course main page with quick edit, recurring meetings get corrupted.

Steps to reproduce:
* Login as teacher
* Go to a course
* Create a Zoom activity
-> Set an arbitrary Topic
-> In the 'schedule' section, set 'When' to some date in the future
-> Check the 'This is a recurring meeting' checkbox
-> Set 'Recurrence' to 'Weekly'
-> Set 'Repeat Every' to 1
-> Set 'Occurs On' to 'Monday' + 'Friday'
-> End date to '10 occurrences'
* Go back to the course overview page
* Open the quick edit form of the Zoom activity's title
* Set the title to _another_ arbitrary title
* Save the title

Expected result:
* Open the editing page of the Zoom activity
* The changed title was set and stored correctly
* The 'schedule' section contains all settings as they were before
* Open the course calendar
* The course calendar contains all events based on the schedule settings as they were before

Actual result:
* Open the editing page of the Zoom activity
* The changed title was set and stored correctly
* In the 'schedule' section the _'Occurs On' setting is empty_
* Open the course calendar
* The course calendar contains changed events which are all scheduled _on sundays_, starting from the sunday which follows the 'When' setting

**Comment by jrchamp** [comment]
Right now, the quick edit is calling the "edit form" function which does a lot of things and expects a lot of data to exist in a very specific format. I'm hoping that #320 will minimize the number of things that the quick edit does so that only the intended changes occur.

Side question: Does the quick edit allow you to edit anything other than the title?

**Comment by jwalits** [comment]
Hey @jrchamp and @alina-kiz 

I had a quick look at the code around the quick edit. It appears as though it does call the `zoom_update_instance($zoom, $mform) {` method, but the $mform object passed here is null and inside the $zoom object the value of the name is already changed.

This means we dont really need to update anything on the plugin's end - we can update the zoom_update_instance function slightly to just call the `$service->update_meeting($zoom);` method to update name on zoom and leave rest of the settings untouched?

Let me know your thoughts around this approach and if it makes sense.

**Comment by alina-kiz** [comment]
Hi everyone,
The quick edit should change only the title.

**Comment by jrchamp** [comment]
Thanks @jwalits and @alina-kiz 

I believe that #320 does exactly what was described, along with making sure that the updated name is also reflected in the calendar events and the gradebook.

**Comment by jwalits** [comment]
Thanks for the link @jrchamp 

That approach outlined in #320 looks good to me. I did a quick test of that code locally and it does appear to resolve this issue.
