### ISSUE TITLE
PHP notices/warnings after  the integration of the tracking fields feature

### ISSUE THREAD

**Issue by alina-kiz** [jrchamp/moodle-mod_zoom#336]
After having upgraded to the latest release of mod_zoom which has #308 / #208 integrated, we are getting these debug warnings in the output of our Moodle cron:

```
PHP Notice:  Undefined property: stdClass::$tracking_fields in /var/www/html/moodle_prod/mod/zoom/classes/task/update_meetings.php on line 164
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/moodle_prod/mod/zoom/locallib.php on line 1172
```
We do not plan to use the tracking feature and haven't configured anything for this feature during the upgrade.

I would be grateful if you could have a look to see if you can get rid of these debug warnings.

**Comment by jrchamp** [comment]
If there are no tracking fields set for the item, then the property does not exist.
https://github.com/ncstate-delta/moodle-mod_zoom/blob/3a2d1c2784c63ed83881954bd2e79b50de265c9f/classes/task/update_meetings.php#L164
Changing it to `$response->tracking_fields ?? array()` should address the issue.

Any chance you are seeing a similar error in the server logs? My guess is that there's other places in the code with similar issues.

**Comment by ndunand** [comment]
Indeed we are seeing huge loads of PHP warnings since the mod_zoom 4.2 update:

```
PHP Notice:  Undefined property: stdClass::$tracking_fields in /.../mod/zoom/classes/task/update_meetings.php on line 164
PHP Warning:  Invalid argument supplied for foreach() in /.../mod/zoom/locallib.php on line 1172
```

No other issues apparent.

**Comment by ndunand** [comment]
I see property existence is checked before trying to access it, which is more robust – for instance here:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/master/lib.php#L119

**Comment by jrchamp** [comment]
While the property existence check is more robust, it unfortunately results in incorrect behavior. Specifically: If a meeting has a tracking fields and that gets synchronized to Moodle, there will be one tracking field listed in Moodle. However, if the tracking fields is deleted from Zoom, then there will be no tracking field property and the change will not be synchronized. Thus, using an empty array when the property does not exist is more accurate behavior.
