### ISSUE TITLE
Shows me the zoom activity in a very large way in the course section and there is no way to change it

### ISSUE THREAD

**Issue by ComicDuck** [jrchamp/moodle-mod_zoom#347]
Hello, my problem is that when creating an activity, it shows it to me in a larger way than the others, causing damage to the visibility of the course, in the image you can better appreciate what I mean. Thanks.

![IA fallo](https://user-images.githubusercontent.com/77419687/146367059-1af14d9c-4a59-465e-9433-a9daaac27c9f.png)
![IA fallo 2](https://user-images.githubusercontent.com/77419687/146368659-1c103921-d7c3-48cc-a40d-3985ec05eabf.PNG)

Here I change the course format so that you can see that the problem is not in the course format, here it does not directly show it due to how large it is, the gray box in the first image should look like the activity highlighted in the second image. Thank you.

![IA fallo 3](https://user-images.githubusercontent.com/77419687/146369346-9b3c1656-1857-47cc-8178-d8285d61e11c.PNG)
![IA fallo 4](https://user-images.githubusercontent.com/77419687/146369527-d8292e37-89da-44bb-a2a3-167cdf542ac7.PNG)

**Comment by jrchamp** [comment]
To tester: Not sure where this is coming from. Our only CSS file is very tiny and I don't think it gets used outside of the module's index.php.

**Comment by armccoy** [comment]
@ComicDuck If you can let us know which theme your Moodle instance is using (or if it is using a custom theme), it will help us be able to replicate the issue as shown in your screenshots. Thanks!

**Comment by armccoy** [comment]
@ComicDuck Since we haven't received any details about the custom theme being used, we'll go ahead and close this issue for now. If you can provide more details, please feel free to reopen it. Also, keep in mind that upcoming changes in Moodle 4 may end up fixing the issue naturally. Thanks!

**Comment by armccoy** [comment]
@ComicDuck Just adding a recent observation for this issue. It appears that the theme in your screenshot is using the Tiles plugin. If there are display issues within the plugin, you may need to adjust some CSS parameters within the plugin or target the plugin's CSS within your Moodle theme. Hope this helps!
