### ISSUE TITLE
Zoom webservice error: Zoom API key not found.

### ISSUE THREAD

**Issue by Kylebrown805** [jrchamp/moodle-mod_zoom#354]
Zoom webservice error: Zoom API key not found.

What does this mean? this is the issue I am in.

**Comment by jrchamp** [comment]
Before you can add a Zoom activity in Moodle, the administrator needs to configure the API key and secret.
https://github.com/ncstate-delta/moodle-mod_zoom/blob/9f99437ac919a4c05df5c604dd2d34f434918607/classes/webservice.php#L120-L125

https://github.com/ncstate-delta/moodle-mod_zoom#installation
