### ISSUE TITLE
Prep for Moodle 4.0

### ISSUE THREAD

**Issue by jrchamp** [jrchamp/moodle-mod_zoom#355]
There are some upcoming enhancements in Moodle 4.0 that we can support: https://docs.moodle.org/dev/Moodle_4.0_developer_update

There may be a way to add that support in a backward compatible way.

As far as discussion points, would you say that the Zoom activity is more "MOD_PURPOSE_COMMUNICATION" or "MOD_PURPOSE_COLLABORATION"? I feel like the _goal_ is learning and collaboration, while the _method_ is communication. Maybe it means something different to each of our users.

**Comment by armccoy** [comment]
I think that while Zoom is certainly a _conduit_ for collaboration (as well as for content and assignments), at its core, it's really a communication tool, much in the same way that the Moodle chat and feedback modules are categorized as communication activities.

**Comment by jrchamp** [comment]
We should make sure to add PHP 8.0 to the matrix we use for our GitHub Action tests.

**Comment by jrchamp** [comment]
If we have any Grunt-related conflicts as a result of changes in Moodle 4.0, we can make sure that we're only performing grunt tests against specific branches. Example: https://github.com/moodlehq/moodle-plugin-ci/pull/158/files

**Comment by jrchamp** [comment]
While we're here, we should probably make sure that the database connections are properly supporting utf8mb4 for MySQL. These lines were recently added to the upstream example https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
```yml
          MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
          MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
```

**Comment by jrchamp** [comment]
For the module purpose constants, they appear to be defined here:
https://github.com/moodle/moodle/blob/1d99ba19a21d57e9f1ed4211a8eeee00e50b7baf/lib/moodlelib.php#L464-L472

Thus in our `function zoom_supports()` function in lib.php, we could add something before the `switch` that is forward compatible like:
```php
if (defined('FEATURE_MOD_PURPOSE') && $feature === FEATURE_MOD_PURPOSE) {
    return MOD_PURPOSE_COMMUNICATION;
}
```
