### ISSUE TITLE
Zoom meeting details are visible to students

### ISSUE THREAD

**Issue by rayjbarrett1** [jrchamp/moodle-mod_zoom#361]
My company and I suspect many others, need to have the Zoom meeting details hidden from students.  Otherwise, students can (and do) share the meeting details with others.  Students only need access to the "Join Meeting" button. The Zoom plugin does not currently have any configuration settings allowing me to hide these details.  
Screenshot: https://www.awesomescreenshot.com/image/23018845?key=216bb5213a75f49f7eb865c0143fc408
Thank you,
Ray

**Comment by jrchamp** [comment]
Hi @rayjbarrett1,

Thank for you reaching out. You can adjust many of these using admin settings or permissions. As an example:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/13a1f5e3e017e5502202eabe92203df7052a1bd7/view.php#L364

From that example, you could remove the mod/zoom:viewjoinurl permission from the students, which can be done at any one of the Moodle site, Moodle category, Moodle course and Moodle activity levels. The meeting host(s) would always be able to see the join URL.

However, please note that for a student to join a meeting their computer must be provided the link at some point no matter what. Thus, anyone with some technical ability could obtain link and re-share it. Additionally, the link is available from within the Zoom client itself after joining a meeting, so it's not something that could be completely resolved through any amount of changes on the plugin side.

If there are items that should not be displayed and which cannot be configured via admin settings or permissions, please let us know.

**Comment by rayjbarrett1** [comment]
Thank you.
In terms of security on Zoom, I have already worked with Zoom so that meeting details are not available in our Zoom meetings and our Zoom meetings are password protected.  We also use a Moodle plugin that does not allow students to copy anything off our site.  Therefore, if we hide the meeting details from them, and they only have the button in the Moodle Zoom activity to enter the meeting, they will not have access to the meeting password. This also is helpful for us because we schedule our Zoom meetings for 30 minutes prior to the start time of the course so that students have a chance to get set up in the meeting.  However, if they see the meeting details, they sometimes get confused about the start time of the course.

**Comment by aduranterres** [comment]
Hi @jrchamp,

I am helping @rayjbarrett1 with this.

Ideally, we'd like to have new options in the plugin configuration, to decide if you want to show/hide blocks:
- Schedule
- Security
- Media

That  way, we could set them all to hide, and only see the "join now" button.

Thanks,
Antonio

**Comment by jrchamp** [comment]
Seems reasonable. It should default to the current behavior but allow the Moodle administrator to configure it. I'll tag this as help wanted and assign you as requested.

**Comment by aduranterres** [comment]
Thanks @jrchamp 

I have worked on this. This is my first try at contributing to someone else's project, so I apologize in advance for the mistakes I will probably make. Hopefully I won't make you waste too much time.
I don't have much experience with Git either, so please let me know if I should do something any other way.

Regarding the code changes: please tell me if you see something that I should do differently and I will try to fix it.
Also, on language: I am not a native English speaker, so the texts are probably  not very good.

Thanks,
Antonio

**Comment by jrchamp** [comment]
> I have worked on this. This is my first try at contributing to someone else's project, so I apologize in advance for the mistakes I will probably make. Hopefully I won't make you waste too much time. I don't have much experience with Git either, so please let me know if I should do something any other way.

Overall, these changes were very clean. Git can be very tricky, for sure. The merge commit is something we might clean up, but it's a small item, not a big problem.

> Regarding the code changes: please tell me if you see something that I should do differently and I will try to fix it. Also, on language: I am not a native English speaker, so the texts are probably not very good.

I thought the text was very good. I only added one comment about word choice, which is great.
