### ISSUE TITLE
"Zoom API key not found" error while installing the plugin

### ISSUE THREAD

**Issue by acquaalta** [jrchamp/moodle-mod_zoom#385]
Hi,

Moodle version: 3.11.6
Plugin version: v4.5.2 (2022051900)

Description of the issue
---------------------------
While installing the plugin in Moodle, at the end of the process, the new settings that the plugin inserted into Moodle are shown.
It seems that if some settings are left empty (at least "Zoom API key" [zoom | apikey]), and then the admin tries to end the install process by clicking on the "Save changes" button at the bottom of the page, the following error page is displayed:

^^^^^^^^^^^^
Zoom webservice error: Zoom API key not found.

×Debug info:
Error code: errorwebservice

×Stack trace:
line 124 of /mod/zoom/classes/webservice.php: moodle_exception thrown
line 1124 of /mod/zoom/locallib.php: call to mod_zoom_webservice->__construct()
line 962 of /mod/zoom/lib.php: call to zoom_list_tracking_fields()
line 2051 of /lib/adminlib.php: call to mod_zoom_update_tracking_fields()
line 8968 of /lib/adminlib.php: call to admin_setting->post_write_settings()
line 26 of /admin/upgradesettings.php: call to admin_write_settings()
^^^^^^^^^^^^

Expected Results
-------------------
An admin could install the plugin without having to fill in required details (like the API key), already during the install process.
It is reasonable to assume that an admin would want to install the plugin at a certain point in time but would like to config it later.

It would be great if you could fix this behavior of the plugin.

Thanks

**Comment by jrchamp** [comment]
I was very confused, because we didn't see this in our installs. It looks like when the tracking fields setting is "updated", there is a callback function:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/84663e0a3d9a27e6290c700e0027e9ded73b5708/settings.php#L324

As the method can be called directly, it should fail gracefully. It may be worthwhile to return a value of some kind (boolean?) so that the scheduled task can still report when an error.

**Comment by jrchamp** [comment]
Thanks @acquaalta for reporting this. I have opened a pull request (#386) that may address this issue. If possible, it would help us a lot if you can confirm that this proposed change resolves the issue you are experiencing.

**Comment by acquaalta** [comment]
Hi,
Thanks a lot for the quick response.
How do I download the most updated code of the plugin that includes your code changes?
It seems that when I click the "Code" button/menu  and then choose the "Download ZIP" option, the files that I get are before your changes.
