### ISSUE TITLE
Switch from JWT to Server-to-Server OAuth before June 2023

### ISSUE THREAD

**Issue by jrchamp** [jrchamp/moodle-mod_zoom#387]
My summary of https://marketplace.zoom.us/docs/guides/build/jwt-app/jwt-faq/
 - JWT is going away June 2023
 - Zoom created Server-to-Server OAuth as a replacement

Overall, we'll want to have a version that uses Server-to-Server OAuth by March 2023 or sooner so people have a chance to install and configure the updated integration. It would also be good to:
 - provide a mechanism for people to switch early
 - maintain the JWT integration until JWT stops working

We'll likely need a new field for each element required to have a fresh token and potentially leverage an OAuth library as needed. If an OAuth library is needed and Moodle already provides one, this may require an increase in our minimum supported Moodle version.

If anyone else has thoughts on this, please share.

**Comment by jrchamp** [comment]
Beyond the technical requirements, a communication plan would be valuable for Moodle administrators. The Zoom administrator may be in an entirely separate part of the organization and will need to get the new app type configured.

The release that includes this functionality should:
- Highlight the new authentication option in the release notes and prioritize it over the legacy JWT option in the settings.
- Provide a reference to Zoom's JWT deprecation documentation.
- If there is an appropriate method, notify Moodle administrators that are using the legacy JWT option.

**Comment by mhughes2k** [comment]
Just going to leave https://docs.moodle.org/400/en/OAuth_2_services here as it looks like it may be feasible to use Moodle's Oauth 2 services to define how to connect to Zoom

**Comment by phette23** [comment]
What does configuring this look like on the Zoom end? I started created a server-to-server OAuth app but when I got to the step where you add scopes I wasn't sure what to do. What scopes does this need? Is there plan to write up a wiki page or something on what it looks like to switch to OAuth? No rush obviously I just want to be prepared.

**Comment by haietza** [comment]
@phette23 The [README.md](https://github.com/ncstate-delta/moodle-mod_zoom/blob/main/README.md) has information about scopes and a link to the Zoom documentation for creating a server-to-server OAuth app.

**Comment by phette23** [comment]
@haietza oops, my apologies. I read the issue, looked at the wiki, but didn't think to check if the readme was updated. Thank you!
