### ISSUE TITLE
Cannot create Zoom meeting activity

### ISSUE THREAD

**Issue by PhilipBeacon** [jrchamp/moodle-mod_zoom#397]
Hi,

When I create new Zoom meeting Activity in Moodle, there is an error message. 

Coding error detected, it must be fixed by a programmer: Templates cannot be placed in sub directories (zoom/breakoutrooms/rooms requested)

Debug info:
Error code: codingerror

Stack trace:
line 113 of /lib/classes/output/mustache_template_finder.php: coding_exception thrown
line 54 of /lib/classes/output/mustache_filesystem_loader.php: call to core\output\mustache_template_finder::get_template_filepath()
line 99 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to core\output\mustache_filesystem_loader->getFileName()
line 82 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to Mustache_Loader_FilesystemLoader->loadFile()
line 657 of /lib/mustache/src/Mustache/Engine.php: call to Mustache_Loader_FilesystemLoader->load()
line 188 of /lib/outputrenderers.php: call to Mustache_Engine->loadTemplate()
line 378 of /mod/zoom/mod_form.php: call to renderer_base->render_from_template()
line 204 of /lib/formslib.php: call to mod_zoom_mod_form->definition()
line 99 of /course/moodleform_mod.php: call to moodleform->__construct()
line 141 of /course/modedit.php: call to moodleform_mod->__construct()

Moodle version: 3.5.18 & 3.6.10
This happened after I updated to v4.6.0 so I updated to v4.6.1 but it doesn't solve the issue.

**Comment by jrchamp** [comment]
Thanks @PhilipBeacon, I did not realize that mustache templates only started supporting subdirectories starting with Moodle 3.8: https://github.com/moodle/moodle/commit/0261d1effafde4aaa2a0b137be2f8edd139e01aa

I'll see if I can rename the files and references so that it does not use subdirectories.

**Comment by PhilipBeacon** [comment]
Hi @jrchamp, thank you for the update. 

Yes, it works now.

**Comment by jrchamp** [comment]
I'm happy to hear that it is working. 😄

We'll plan to get the fix released in a proper version, hopefully this week.
