### ISSUE TITLE
Cache the results of get_user()

### ISSUE THREAD

**Issue by aduranterres** [jrchamp/moodle-mod_zoom#401]
Create a helper function that caches the results of get_user() so that it's only ever called once per page load.

**Comment by aduranterres** [comment]
Please @jrchamp can you provide any pointers on how you would like this done, or if you prefer that I leave this one to you.

**Comment by jrchamp** [comment]
I have some code in mind for this. 😄 I'll link the PR soon.

**Comment by sgrandh3** [comment]
Verified the changes by measuring the page loads with and without the changes. After the change, the page loaded in an average of 40% faster in the measured test scenarios
