### ISSUE TITLE
Locked settings are no longer applied in 4.7.0

### ISSUE THREAD

**Issue by krab-stik** [jrchamp/moodle-mod_zoom#406]
Starting with version 4.7.0, when the `requirepasscode` setting is locked by an administrator, it is not properly enforced in the Zoom activity creation form. The lock icon does not appear near the label and the user is allowed to uncheck the box.

The new `definition_after_data()` method that was added in `mod_form.php` should call `parent::definition_after_data()`. This is where the locking of form elements was performed in previous versions.

**Comment by jrchamp** [comment]
Thank you! That's good to know.

**Comment by jrchamp** [comment]
@krab-stik If you are able to confirm that the fix in the linked Pull Request fixes the issue, that would help get this merged.

**Comment by krab-stik** [comment]
Works like a charm! :+1:
