### ISSUE TITLE
Change the css identifiers to prevent conflicts. 

### ISSUE THREAD

**Issue by danielcifuentesopen** [jrchamp/moodle-mod_zoom#411]
Hi.

In the new version 2022092200, there are new elements added to the `zoom/styles.css` file. These element doesn't include the "mod_zoom" in the name to prevent some conflicts with existing identifiers in other moodle plugins. 

The elements added are: `#meeting-room-participants`, `#meeting-room-participant-groups`, `#meeting-rooms-list`, `#breakout-rooms-table`, `#breakout-rooms-table`, `#breakout-rooms-table`, `#breakout-rooms-table`. It will be better to change this identifiers with ones that include "mod_zoom" just to separate them and prevent future conflicts. 

Thanks a lot.

**Comment by jrchamp** [comment]
Thank you @danielcifuentesopen. This seems like a good way to avoid potential conflicts and it should be easy for us to adjust.
