### ISSUE TITLE
Moodle description displayed twice at top of activity

### ISSUE THREAD

**Issue by Laur0r** [jrchamp/moodle-mod_zoom#414]
When clicking on the zoom activity, you see the description repeated.
This is on Moodle 4.0.3 with all plugins up-to-date. This seems to be true on all of our created zoom activities since the upgrade to Moodle 4.
![Zoom_error](https://user-images.githubusercontent.com/35337130/193816703-8ab8daab-29d0-409d-8ba4-e9e9ed2de4e4.png)

**Comment by jrchamp** [comment]
Seems like a bug, we'll need to investigate.

**Comment by haietza** [comment]
@jrchamp It looks like core changed the way they are displaying the description text, along with activity completion. Most third party plugins we use are seeing the same duplication of description content.
