### ISSUE TITLE
trouble switching to OAuth, "Undefined property: moodle_exception::$zoomerrorcode" errors

### ISSUE THREAD

**Issue by phette23** [jrchamp/moodle-mod_zoom#415]
After looking at the readme, I've tried to switch to server-to-server OAuth on a test server but been unsuccessful. Here are the steps I took:

- created a s2s app in Zoom App Marketplace
- gave it _all_ scopes listed in the readme (I started with just a subset of the ones we need but then added the rest when I began running into problems; the full list did not fix the issue)
- activated it
- pasted the account id, client id, and client secret from the **App credentials** page in Zoom into the plugin's settings

When I save, I always see an error that the HTTP/2 response wasn't closed cleanly:
<img width="713" alt="Screen Shot 2022-10-06 at 10 05 28 AM" src="https://user-images.githubusercontent.com/1024833/194375218-71b6e40a-3453-45b6-9aec-215027a07116.png">

We have debugging on and this error is also displayed and in our server logs:

`PHP Notice:  Undefined property: moodle_exception::$zoomerrorcode in /bitnami/moodle/mod/zoom/locallib.php on line 535, referer: MOODLE_URL/my/`

I saw that line 535 is in the `zoom_is_user_not_found_error` function. I don't know why user lookups would fail, the app works fine with JWT authentication. I tried changing the apiidentifier setting from email to username but that didn't fix the issue. Am I doing something wrong? Did I miss something in setting up the OAuth app? I think I probably set something up wrong but there also appears to be another problem in that the error code is not defined.

**Comment by jrchamp** [comment]
I think this is related to the default behavior of cURL being different between the systems we're using to test and your system.

My guess is that your system is defaulting to HTTP/2 when possible. The suggested workarounds seem to be forcing HTTP/1.1:
```php
curl_setopt($curl, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
```

I'll try to see if I can reproduce the issue on my system.

**Comment by phette23** [comment]
We're using the [Bitnami Docker image](https://hub.docker.com/r/bitnami/moodle) if that's helpful, v3.10.4. So Debian. I'm not sure where to put that `curl_setopt` line if you want me to test...it looks like Moodle has an object wrapper around `curl`.

**Comment by jrchamp** [comment]
Probably immediately after these lines: https://github.com/ncstate-delta/moodle-mod_zoom/blob/faf390dc031a114248cb8f688264a32e441da548/classes/webservice.php#L981-L982

**Comment by phette23** [comment]
Adding that line seemed to fix the problem. The connection status on the Zoom Meeting settings page is green again. I tested creating and joining a meeting without any trouble. I don't know if there are other implications of forcing HTTP/1.1 though.

**Comment by jrchamp** [comment]
The main problem with forcing HTTP/1.1 would be if Zoom's OAuth endpoint stops supporting it. HTTP/2 has had some mixed success to the point that HTTP/3 (which avoids TCP's lack of support for multiplexing) is probably the only reasonable successor that might supplant HTTP/1.1 as the primary option. However, I doubt that will happen soon. Forcing the use of HTTP/1.1 should hopefully only be necessary for a short period of time until we can hopefully work with Zoom to resolve whatever issue exists with HTTP/2 connections. Wish us luck that we're able to reproduce the issue with a minimal test case tomorrow. :crossed_fingers:

**Comment by phette23** [comment]
Thanks! FWIW I didn't see the issue with the latest [Bitnami Moodle image](https://github.com/bitnami/containers/tree/main/bitnami/moodle#how-to-use-this-image) on 4.0.4. I wonder if that means it's some kind of underlying Debian or PHP issue. But I tried with a fresh container using our version (docker.io/bitnami/moodle:3.10.4) and recreated the issue issue. Basic steps were: use the Bitnami [docker-compose.yml](https://github.com/bitnami/containers/blob/main/bitnami/moodle/docker-compose.yml), edit the Moodle image version to 3.10.4, `docker-compose up -d`, login (user/bitnami) at http://localhost, go to Admin > Install Plugins, install latest Zoom plugin release, add S2S Oauth into its settings, revisit the plugin's settings page, see connection error.

**Comment by jrchamp** [comment]
Bitnami's image for Moodle 3.10.4 was using Debian 10 instead of Debian 11. It's possible that the issue is due to a bug in the versions of PHP and/or cURL that were used. Unfortunately, we were unable to reproduce the issue as our versions of cURL were either new enough to not have a problem or old enough to not support HTTP/2 (the PHP constant was not defined). We'll plan to add the HTTP/1.1 workaround for now and plan to remove the workaround when Zoom deprecates support.
