### ISSUE TITLE
Auto recording turned off on all activities

### ISSUE THREAD

**Issue by emmarichardson** [jrchamp/moodle-mod_zoom#416]
Not sure if the setting changed on the Zoom side or on the Mod side but suddenly all my meetings that were set to auto record stopped recording - I discovered that the setting which was originally must have been pulling from zoom now was showing as None instead of Null...

**Comment by jrchamp** [comment]
Likely a regression caused by #390

The default for `option_auto_recording` is `none`. If your environment defaults to automatically recording to Zoom's Cloud, you may want to run: `UPDATE mdl_zoom SET option_auto_recording = 'cloud';` so your previously created meetings are accurately configured.

Then, make sure to set the default value for the admin-level setting `zoom/recordingoption` to the Cloud or User Default setting so that the newly created meetings are accurately configured.

Please let me know if that resolves the issue. I'm thinking it might not fully resolve it, especially if you are not allowing recording options to be changed...

**Comment by emmarichardson** [comment]
Yes, I did run that on my database to resolve.  It was more a shock that the setting would change like that and have that effect - especially when it was set to autorecord for that account.  I wasn't sure if you had warned people - you might have done and I might have missed it.

**Comment by jrchamp** [comment]
When new features are added, I try and put all of the new admin-level and activity-level settings in the release notes:
- https://github.com/ncstate-delta/moodle-mod_zoom/releases/tag/v4.7.0
- https://github.com/ncstate-delta/moodle-mod_zoom/blob/main/README.md#changelog

However, I incorrectly assumed that automatic recording was always "off" for activities that this plugin was creating. Instead, Zoom's API seems to be using the user's defaults on the Zoom side in some cases. So by sending a value from the Moodle side, we are no longer automatically getting the user's default value in Zoom.

**Comment by emmarichardson** [comment]
Ok, that makes sense.  You can close this out if you want.  I just wasn't sure if you were aware of what had happened here or not.  Thanks for the clarification.

**Comment by jrchamp** [comment]
Instead of `'none'`, a better default would probably be to use the user's default setting as this should mirror the previous behavior. We'll definitely need to do something about this, so I'll keep the issue open. I really appreciate your feedback on this.

**Comment by emmarichardson** [comment]
Yes, that would probably have been a better solution.  Luckily we caught it pretty quick and only lost a couple of sessions that should have been recorded.

**Comment by jrchamp** [comment]
Notes for upcoming testing:

- [ ] Set your Zoom account default to automatically record to Cloud.
- [ ] Set the Moodle admin-level setting for automatic recording to User Default.
- [ ] Schedule a meeting in Moodle and make sure it defaults to 'cloud', save and make sure it is set to Cloud in Zoom.
- [ ] Schedule a meeting in Moodle and set the recording to 'none', save and make sure it is set to not record in Zoom.
- [ ] Set the Moodle admin-level setting for automatic recording to Cloud.
- [ ] Set the Moodle admin-level setting for allow change recording to `false`.
- [ ] Schedule a meeting in Moodle, save and make sure it is set to Cloud in Zoom.
- [ ] Set your Zoom account default to not automatically record.
- [ ] Schedule a meeting in Moodle, save and make sure it is set to Cloud in Zoom.

**Comment by jrchamp** [comment]
When this is implemented, we will want to revert the changes from #470.
