### ISSUE TITLE
Cron tasks broken in latest version of the code

### ISSUE THREAD

**Issue by lexxkoto** [jrchamp/moodle-mod_zoom#420]
In the latest release of the Zoom plugin, the scheduled task 'update_meetings' fails with the following error:

Server Time: Thu, 20 Oct 2022 12:18:21 +0100

Execute scheduled task: Update meeting settings from Zoom (mod_zoom\task\update_meetings)
... started 12:18:21. Current memory use 4.8MB.
!!! Exception - Call to undefined function mod_zoom\task\zoom_webservice() !!!

It looks like the scheduled task is trying to use the zoom_webservice() function before the require_once() line that loads the function:

<img width="446" alt="Screenshot 2022-10-21 at 11 16 56" src="https://user-images.githubusercontent.com/7327138/197174554-d4b76fe9-dfe7-4178-8fb7-c2d29c32a11e.png">

**Comment by jrchamp** [comment]
Thanks @lexxkoto! I'll get something fast tracked.
