### ISSUE TITLE
Missing language string

### ISSUE THREAD

**Issue by aspark21** [jrchamp/moodle-mod_zoom#423]
mod_zoom: main branch latest
Moodle: MOODLE_311_STABLE latest

core_cache\administration_helper_test::test_get_summaries
Unexpected debugging() call detected.
Debugging: String does not exist. Please check your string definition for cachedef_oauth/mod_zoom
* line 10499 of /lib/moodlelib.php: call to debugging()
* line 623 of /cache/classes/definition.php: call to lang_string->__construct()
* line 205 of /cache/classes/administration_helper.php: call to cache_definition->get_name()
* line 100 of /cache/tests/administration_helper_test.php: call to core_cache\administration_helper::get_definition_summaries()
* line 1545 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to core_cache\administration_helper_test->test_get_summaries()
* line 1151 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit\Framework\TestCase->runBare()
* line 726 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 903 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestResult->run()
* line 672 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestCase->run()
* line 672 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
* line 672 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
* line 673 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit\Framework\TestSuite->run()
* line 143 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\TestRunner->run()
* line 96 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\Command->run()
* line 97 of phpvfscomposer:///vendor/phpunit/phpunit/phpunit: call to PHPUnit\TextUI\Command::main()
* line 118 of /vendor/bin/phpunit: call to include()

/var/www/html/lib/phpunit/classes/advanced_testcase.php:88
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97

**Comment by jrchamp** [comment]
Thanks @aspark21! I opened a pull request that should resolve this issue.
