### ISSUE TITLE
Bug: Passcode field rules do not reflect passcode policy from Zoom server

### ISSUE THREAD

**Issue by sascha-serwe** [jrchamp/moodle-mod_zoom#424]
In an earlier version there was a bug that the plugin did not use the passcode policy from zoom server and therefore produced invalid passcodes. This issue was fixed #160 

However, it seems that in version 4.8.1 (2022102000) this bug (or a related issue) is back again: if I try to plan a zoom meeting, the generated default passcode does not match our requirements (in my case 8 characters necessary vs default 6 characters).

If I change the pascode manually to 8 characters, it works. I can save the meeting.
 If I do not change the passcode and try to save, I get the following error message:
 
> Zoom received a bad request: {$a}
> 
> [More information about this error](http://docs.moodle.org/311/en/error/zoom/errorwebservice_badrequest)
> 
> Debug info:
> Error code: errorwebservice_badrequest×Dismiss this notification
> Stack trace:
> line 274 of /mod/zoom/classes/webservice.php: zoom_bad_request_exception thrown
> line 717 of /mod/zoom/classes/webservice.php: call to mod_zoom_webservice->make_call()
> line 102 of /mod/zoom/lib.php: call to mod_zoom_webservice->create_meeting()
> line 128 of /course/modlib.php: call to zoom_add_instance()
> line 168 of /course/modedit.php: call to add_moduleinfo()
> ×Dismiss this notification
> Output buffer: <br /> <b>Notice</b>: Trying to get property 'message' of non-object in <b>/moodle/application/htdocs/moodle/eval/mod/zoom/classes/webservice.php</b> on line <b>274</b><br /> <br /> <b>Notice</b>: Trying to get property 'code' of non-object in <b>/moodle/application/htdocs/moodle/eval/mod/zoom/classes/webservice.php</b> on line <b>274</b><br />

This does not seem to be related the the new oAuth method (and related rights/scopes of the app)  At least I get the same errors if I switch back to jwt.

**Comment by jrchamp** [comment]
I believe that #408 will resolve this issue as it will provide more accurate passcode information for the specific user without requiring account-level permissions. Would you be able to try it?

**Comment by jrchamp** [comment]
v4.9.0 has been released with the user-level settings fix. Please let me know if that helps resolve the automatically generated passcode issue.

I will try to address the error handling problem when an invalid passcode is supplied.

**Comment by sascha-serwe** [comment]
We installed v4.9.0 and I can verify, that the passcode issue ist solved. 

To be precise: the default length of the passcode for new meetings is is now 8 characters - as defined by our zoom account.

**Comment by sascha-serwe** [comment]
Can be closed. I used the wrong button in my previous comment.
