### ISSUE TITLE
Resource not exists while editing meeting with not owner

### ISSUE THREAD

**Issue by juanbrunetmf** [jrchamp/moodle-mod_zoom#430]
When I try to edit a meeting from moodle with an user which not owned the zoom meeting, plugins throw error
```
The resource does not exists
More information about this error
×Debug info:
Error code: errorwebservice_notfound
×Stack trace:
line 276 of /mod/zoom/classes/webservice.php: zoom_not_found_exception thrown
line 456 of /mod/zoom/classes/webservice.php: call to mod_zoom_webservice->make_call()
line 1286 of /mod/zoom/locallib.php: call to mod_zoom_webservice->get_user_settings()
line 536 of /mod/zoom/mod_form.php: call to zoom_get_user_settings()
line 214 of /lib/formslib.php: call to mod_zoom_mod_form->definition()
line 130 of /course/moodleform_mod.php: call to moodleform->__construct()
line 150 of /course/modedit.php: call to moodleform_mod->__construct()
```

this behavior not happens at 4.3.2 but in 4.8.1 and 4.9.0 testing and it occurs even with the admin role

is that the expected behavior?

**Comment by jrchamp** [comment]
Thanks @juanbrunetmf. This is most likely a regression from when the automatic recording functionality was added. This may be addressed by #422. We'll need to make sure to do more testing with admin-style accounts that do not have corresponding Zoom accounts.
