### ISSUE TITLE
Inconsistency between the DB and the schema defined in install.xml

### ISSUE THREAD

**Issue by fabianbatioja** [jrchamp/moodle-mod_zoom#432]
There is a small inconsistency between what is defined in install.xml and what is in the database that originated in update `2022031600`.

What happens is that the fields `show_schedule`, `show_security` and `show_media` in the table `zoom` in `install.xml` file are defined as fields that do not allow null as value. However, when these fields were created in `upgrade.php` in the upgrade block `2022031600` the field was left null in the method to define it as non-null. What causes that if the plugin was updated that field remains as not null false and if it is installed as not null true.

I have not found any problems for the user due to this, however it may cause problems in the future. Running `admin/cli/check_database_schema.php` on an updated db shows the difference.

**Comment by jrchamp** [comment]
Thanks @fabianbatioja ! We'll take a closer look at this soon.

**Comment by foxlapinou** [comment]
Hi,
I use the latest (4.9.1) version of the plugin, and have also seen this with the checking tool.
Details are:

```
 * column 'show_schedule' should be NOT NULL (I)
 * column 'show_security' should be NOT NULL (I)
 * column 'show_media' should be NOT NULL (I)
 * column 'option_auto_recording' should be NOT NULL (C)
 * column 'option_auto_recording' has default 'NULL', expected 'none' (C)
```

**Comment by foxlapinou** [comment]
Hi,
Just to confirm the problem is still here with latest existing plugin version. Hope one can fix it (soon), to avoid any risk.
