### ISSUE TITLE
Undefined variable zoomapiidentifier

### ISSUE THREAD

**Issue by haietza** [jrchamp/moodle-mod_zoom#435]
Debugging revealed a notice when attempting to create a meeting:

PHP Notice:  Undefined variable: zoomapiidentifier in /var/www/html/mod/zoom/mod_form.php on line 433, referer: /course/modedit.php?add=zoom&type=&course=xxx&section=0&return=0&sr=0
PHP Stack trace:, referer: /course/modedit.php?add=zoom&type=&course=xxx&section=0&return=0&sr=0
PHP   1. {main}() /var/www/html/course/modedit.php:0, referer: /course/modedit.php?add=zoom&type=&course=xxx&section=0&return=0&sr=0
PHP   2. mod_zoom_mod_form->__construct() /var/www/html/course/modedit.php:150, referer: /course/modedit.php?add=zoom&type=&course=xxx&section=0&return=0&sr=0
PHP   3. mod_zoom_mod_form->__construct() /var/www/html/course/moodleform_mod.php:130, referer: /course/modedit.php?add=zoom&type=&course=xxx&section=0&return=0&sr=0
PHP   4. mod_zoom_mod_form->definition() /var/www/html/lib/formslib.php:214, referer: /course/modedit.php?add=zoom&type=&course=xxx&section=0&return=0&sr=0

Looks like $zoomapiidentifier is reference in line 433 but not declared beforehand. 

Many thanks for taking a look at this!

**Comment by smbader** [comment]
Regression from pull request #422

Looks like we should be using $zoomuserid
`$securitysettings = zoom_get_meeting_security_settings($this->current->host_id ?? $zoomuserid);`
