### ISSUE TITLE
Delete meeting recordings doesn't  ends

### ISSUE THREAD

**Issue by juanbrunetmf** [jrchamp/moodle-mod_zoom#437]
With a site with almost 200k meeting recordings, we cannot finish the task delete_meeting_recordings.

I think  is that for every zoom recording, fetch all recordings for the unique meetinguuid, and de-populate the recording array as check API $service->get_recording_url_list($meetinguuid) get associated recordings.

At the end of this process (that could take easy more than one day in my case), only then starts the deletion process of the remaining zoomrecordings. Of course, database has gone away at this time (extending timeouts is a solution too, but zoom recording management could be better)

There is any chance that the deletion takes action for every meeting and not at the end?
I suggest fetch all local meetingsuuid, iterate for each to compare local recordings for that meetinguuid against the api query to zoom and then process the deletion for the diff.

**Comment by jrchamp** [comment]
Hi @juanbrunetmf! I have opened a pull request that should implement the suggestion you provided. If you could, please take a look and see if this helps resolve the issue.

**Comment by juanbrunetmf** [comment]
sorry for the late review for this.

I notice the changes and seems legit (I am not dev... yet). Reorder the deletes for each meeting should help the process. 
Thanks in advance and we will wait until next release that join this change to use this on production
