### ISSUE TITLE
JWT deprecation on June 2023

### ISSUE THREAD

**Issue by izendegi** [jrchamp/moodle-mod_zoom#441]
Hi, 

I copy here one comment [at the plugin database](https://moodle.org/plugins/mod_zoom) just in case you didn't notice it:

_Hello Jonathan,
the JWT authentication method will be deprecated on June 1, 2023 and replaced by the Server-To-Server OAuth method.
Will the Zoom Meeting plugin for Moodle be impacted?
Thank you_

I've checked that the Zoom shows that message in our console too:
![irudia](https://user-images.githubusercontent.com/5556433/210323176-d9bf73f8-d6f4-48cb-8461-c60bb8fcbfa7.png)

**Comment by jrchamp** [comment]
Hi @izendegi 

Server-to-Server OAuth support was added by #403 and released with [v4.8.0](https://github.com/ncstate-delta/moodle-mod_zoom/releases/tag/v4.8.0) on September 29, 2022. To switch to Server-to-Server OAuth:

1. [Create and configure a Server-to-Server OAuth app](https://github.com/ncstate-delta/moodle-mod_zoom#server-to-server-oauth)
2. [Update the plugin settings in Moodle](https://github.com/ncstate-delta/moodle-mod_zoom#installation)

If you have any additional questions, please let us know. I'll copy this to the plugin database website for completeness.
