### ISSUE TITLE
Finished Zooms show up in My Overview block

### ISSUE THREAD

**Issue by nstefanski** [jrchamp/moodle-mod_zoom#450]
Not sure if this affects other versions, but noticed in 4.1 that Zoom meetings are still shown in the My Overview block after they're no longer available. I'll share a patch momentarily.

**Comment by jrchamp** [comment]
Hi @nstefanski 

I trust that your patch fixes the issue, but I'm not sure what I should or shouldn't be seeing in the "Course overview" block (block_myoverview). Can you explain or provide some images showing the problem in action so that we can test it on our system?
