### ISSUE TITLE
Opening zoom link on mobile when moodle is hosted in a webview fails

### ISSUE THREAD

**Issue by noamamit92** [jrchamp/moodle-mod_zoom#454]
I believe it has to do with view.php:

 $link = html_writer::tag('form', $buttonhtml, ['action' => $aurl->out_omit_querystring(), 'target' => **'_blank']**);

When in a webview , the attempt to open  anew window/tab fails and the link does not open.

Is there a solution or workaround for this?

**Comment by jrchamp** [comment]
Hi @noamamit92,

If you remove the `, 'target' => '_blank'` code, does that resolve the issue for you? If so, what is the difference in behavior for desktop? In general, _blank is not ideal for accessibility and usability reasons, so if we can remove it, it might be for the best.

**Comment by sgrandh3** [comment]
Hi @noamamit92 ,
We tried to reproduce it on both iOS and Android mobile web views, but are unable to reproduce the issue. 
Can you provide more detailed steps if you are still encountering the issue?

**Comment by noamamit92** [comment]
Hi @sgrandh3 ,

We tried pin pointing the problem and I think this is the challenge:
Once you click on the link to the moodle zoom plugin, We no longer control what is happening on the page (us being the app that opened the webview). 
Your code kick in and eventually it tries to open a zoom link but that link will not open on a webview, we thought it might be related to the target="_blank" issue but it seems its not, It seems we will have to handle in our app and redirect based on the scheme to open in zoom.
If this ran on the native default browser (i.e: Chrome) then it would open zoom directly as it handles the zoomus:// scheme itself.
I'm not sure there is anything that can ve done on your side, so I am closing the issue
