### ISSUE TITLE
This meeting cannot be found on Zoom but it exists in zoom

### ISSUE THREAD

**Issue by swap83** [jrchamp/moodle-mod_zoom#458]
Hello,
sorry for my english :).
In version 4.9.2 we receive this error: This meeting cannot be found on Zoom. You can recreate it or delete it completely but the meeting exists.

**Comment by jrchamp** [comment]
Hi @swap83,

Thank you for reporting this error. Is the error showing for all meetings or only a few? Were those activities created on an older version or were they created on 4.9.2?

**Comment by swap83** [comment]
> Is the error showing for all meetings or only a few? 
Many meetings. Not all.

> Were those activities created on an older version or were they created on 4.9.2?
Yes.

Now i use this workaround:
in this file:  /var/www/html/moodle/mod/zoom/view.php
I edited from 69th line;

`
#if ($zoom->exists_on_zoom == ZOOM_MEETING_EXPIRED) {
#    $showrecreate = true;
if (0) {  
        echo ""; 
} else {`
```

**Comment by jrchamp** [comment]
There was an error in the Italian translation and I have submitted a change in AMOS to resolve that part of the issue.

For the ZOOM_MEETING_EXPIRED, it's possible that the API returned a lot of incorrect failure messages. #444 may be related, as I've been seeing a number of odd Zoom API errors here and there. You may be able to update the exists_on_zoom value directly in the database for the affected meetings. If you want to try resetting them all: `UPDATE mdl_zoom SET exists_on_zoom = 1`
