### ISSUE TITLE
Server-to-Server OAuth - Connection failed: Invalid access token

### ISSUE THREAD

**Issue by DLM-unipd** [jrchamp/moodle-mod_zoom#473]
We tested a couple of Moodle instances with a new Server-to-Server OAuth zoom application following the plugin instructions, but after a couple of days both crons give us a "webservice Zoom: Invalid access token" error.

After that, the plugin setting page says that
"Connection status: Connection failed: Invalid access token"
It seems related to the expiration of the token, but it is quite random, sometimes it normally says "Connection status: Connection working." but refreshing the page it switches to "failed".

Cron error (Italian translation):
Scheduled task failed: Ricevi da Zoom il report della riunione (mod_zoom\task\get_meeting_reports),Si è verificato un errore nel webservice Zoom: Invalid access token

Moodle versions: 3.9 and 3.11
mod_zoom version: 4.10.0

**Comment by haietza** [comment]
Are you using the same credentials on all instances? If so, that is causing the issue. When a new token is requested, it automatically invalidates the previous token, regardless of expiration. If you  have multiple instances using the same credentials to request the token, the requests will overlap each other, causing the token being used by one instance to be invalidated by a request from another instance. To remedy, create a unique server to server oauth app in Zoom for each instance of Moodle.

**Comment by DLM-unipd** [comment]
Yes, we are using the same app with the same credentials, following Jonathan's answer on this very topic:

> Server-to-Server OAuth apps are very flexible. As they are not assigned to a specific domain, you can use the same credentials for multiple Moodle instances (similar to JWT). If - for whatever reason - you wanted to have multiple Server-to-Server OAuth apps, you can, but it is not required. Example: If there was a Moodle instance where you wanted to restrict the level of access, it is possible to grant only the required OAuth contexts for that instance.

**Comment by haietza** [comment]
It is not required, in the sense that the credentials will be valid and work for API calls on multiple sites. However we recently ran into repeated instances of the invalid access token error and my best guess was that is was the multiple instances overlapping use of the token (with different user accesses, different cron timing, etc). I created separate oauth apps in Zoom for each instance, and we have not seen the error since.

**Comment by DLM-unipd** [comment]
Thanks for sharing!
@jrchamp maybe it should be investigated and documented

**Comment by jrchamp** [comment]
Thanks all! We should definitely add that to the documentation. I had not quite realized just how important it is that multiple Moodle installations might invalidate tokens. Thankfully, the plugin's use of Moodle's caching avoids the potential conflicts from multiple web servers that are part of the same Moodle install.

**Comment by jrchamp** [comment]
Zoom may have fixed the underlying issue yesterday, June 20, 2023. A Zoom employee posted:

> You should be able to request multiple tokens and the request of a new one won’t invalidate the previous one

Reference: https://devforum.zoom.us/t/invalid-access-token-in-server-server-oauth/90041/6?u=jonathan_champ

**Comment by jrchamp** [comment]
Here's the official announcement: https://devforum.zoom.us/t/multi-access-tokens-launched-for-s2s-apps/90527

Quoting [the updated documentation on these tokens](https://developers.zoom.us/docs/internal-apps/s2s-oauth/#access-token-best-practices):

> You can generate multiple access tokens for a server-to-server OAuth app without invalidating the previous tokens.
