### ISSUE TITLE
Bug: "cannot require a CSS file before <head> has been printed" when editing default activity completion

### ISSUE THREAD

**Issue by phette23** [jrchamp/moodle-mod_zoom#478]
If I go to a course > course completion > default activity completion > select Zoom and **Edit** its activity completion defaults, I receive this error: `Cannot require a CSS file after &lt;head&gt; has been printed.`

<img width="1016" alt="Screenshot 2023-05-10 at 1 46 13 PM" src="https://github.com/ncstate-delta/moodle-mod_zoom/assets/1024833/14b73790-1bec-4168-a5ee-56dd59b1b512">

When you click the error's **Continue** button, it takes you back to the default activity completion settings page, so functionally this bug makes it impossible to edit Zoom's defaults.

Moodle: 4.0.5 (Build: 20221114)
Zoom: v4.10.1 2023021400 (I encountered on v4.10.0 also before I realized you had a new release)

**Comment by jrchamp** [comment]
Thanks @phette23! We were able to reproduce the issue and will work on a fix.
