### ISSUE TITLE
Course reset always remove zoom user data.

### ISSUE THREAD

**Issue by carlosalal** [jrchamp/moodle-mod_zoom#480]
On the function zoom_reset_userdata doens't check the value of reset_zoom_all. When a user reset a course without marking the checkbox for reset_zoom_all, the call to zoom_reset_userdata remove everything anyway.
Zoom_reset_data function needs somethings like 
if (!empty($data->reset_zoom_all)) {
to check this value to delete user data or not.

**Comment by jrchamp** [comment]
Thanks @carlosalal! This change looks like exactly what needs to happen.
