### ISSUE TITLE
Repeating weekly meeting

### ISSUE THREAD

**Issue by morceraTadel** [jrchamp/moodle-mod_zoom#487]
Hello,

I'm creating a recurring meeting that repeat weekly, but at the begginning of the week, my meeting is changed to sunday instead of the day I enabled. Also the checks on the field "Occurs on" are all disabled, in this case, saturday should be enabled.

![1](https://github.com/ncstate-delta/moodle-mod_zoom/assets/102580306/7aa10fb3-eaea-4a78-8b01-ec2f4591c318)

Thank you!

**Comment by jrchamp** [comment]
Thanks @morceraTadel for opening the issue. The image shows what the meeting settings display after the activity has been created. If possible, can you please also include an image which shows what the meeting settings are when creating the meeting? That way, we can try to reproduce the issue using the same inputs and outputs.

**Comment by morceraTadel** [comment]
These are the initial settings, the difference is the day checked.
![2](https://github.com/ncstate-delta/moodle-mod_zoom/assets/102580306/13402faa-f6bf-4591-8df3-3d94c59518fb)

Thank you so much for your response!

**Comment by jrchamp** [comment]
Hi @morceraTadel,

I've never been able to reproduce this issue. Is it still a problem on the latest version?

**Comment by morceraTadel** [comment]
Hello @jrchamp 

Yes, it's solved on the latest version.

Thanks!!
