### ISSUE TITLE
PHP 7.0 constants visibility Issues

### ISSUE THREAD

**Issue by rlaneIT** [jrchamp/moodle-mod_zoom#489]
Hi,

I have updated teh plugin to the latest version for 3.4+ but are running PHP. The plugin errors out and prevents many other pages loading.

'const' (T_CONST), expecting variable (T_VARIABLE) 

Its seems be be an issue with how the constants are declared in the webservice.php that isnt compatible with PHP 7.0.

Is there a work around for this for PHP 7.0 as a quick fix?

**Comment by jrchamp** [comment]
Sorry @rlaneIT! Breaking PHP 7.0 compatibility was not intended, but is harder and harder to avoid. PHP 7.1 supports class constant visibility.

As a workaround, you would need to replace `public const` and `private const` with just `const`. The 3 files are:

- classes/invitation.php
- classes/task/get_meeting_reports.php
- classes/webservice.php

The change would be the opposite of https://github.com/ncstate-delta/moodle-mod_zoom/commit/be3dec81b07a6199618595599a0c4e50723751ce

**Comment by jrchamp** [comment]
The plan is to release a 4.10.3 version that has this commit reversed. With version 5.0.0, we'll plan to drop support for PHP 7.0 and Moodle 3.4, 3.5 and 3.6.
