### ISSUE TITLE
Grade/Completion happens when registering for the Zoom session

### ISSUE THREAD

**Issue by tbeachy** [jrchamp/moodle-mod_zoom#490]
Hello,
I tested this beforehand, and thought it was working properly to issue a completion when the student joins the live Zoom session.  But now I have tested it to issue the completion simply when the student pre-registers for the Zoom session by clicking the "Register" button.  
Is this intended?  For us it is a problem.  I had seen somewhere else in the issue  queue comments that a grade or completion were issued when a student "joins" the session.
Any clarification or help on this is much appreciated.

**Comment by tbeachy** [comment]
I thought that perhaps it was due to having both "Student must view this activity to complete it" and "Student must receive a grade to complete this activity" checked under the Activity Completion options.   But I turned off the first one (leaving only the grade option), and tested again as a student, but it still completes the student immediately upon registering, even though the live session is scheduled for two months from now.

**Comment by jrchamp** [comment]
That does appear to be a bug. The pre-register workflow should not mark the activity as complete, trigger the event or set the grade. The non-registration workflow is doing the correct thing and the just-in-time registration workflow is doing the best it can.

**Comment by tbeachy** [comment]
Thanks for looking into it!
