### ISSUE TITLE
Improvement: Show date and time for Zoom meeting directly on the course page

### ISSUE THREAD

**Issue by cdipe** [jrchamp/moodle-mod_zoom#493]
It would be good for the users, and more consistent with core moodle activities, to show the zoom date & time settings directly on the course page by the link to the activity.

**Comment by jrchamp** [comment]
@cdipe Thank you for the suggestion! Can you provide a visual example of a core Moodle activity that you think does this well?

For Zoom, we have three types of dates to consider: Single meeting; Recurring meeting no date; Recurring meetings with specific dates. For single meetings, showing the date/time makes sense. For recurring meetings, displaying "Recurring" or "Recurring, no fixed time" might be fine. However, for the recurring meetings with multiple dates, we need to decide whether to show *all* of the dates (data overload?) or only the next upcoming date(s) (what do we show if all upcoming dates have passed?).

**Comment by cdipe** [comment]
@jrchamp hi!
In Assignments there are due / overdue dates, and in quizzes there are start and end dates. (Image 1)

To avoid clutter, only the most necessary info should be shown. The vital information to show for **single meetings** is the start date, and info that the meeting is ended (when passed set meeting time). (Image 2 and 3)

For **recurring meetings with set dates**, the next start date should show when the end time of the ongoing meeting is passed. (Image 1)

For **recurring meetings w/o set dates** maybe there is no date info needed at all?

<img width="793" alt="zoom m4 ended" src="https://github.com/ncstate-delta/moodle-mod_zoom/assets/14754240/6e802837-1ccb-4838-8864-d15d6cd45f84">
<img width="796" alt="assignment m4" src="https://github.com/ncstate-delta/moodle-mod_zoom/assets/14754240/0594f3d1-24a7-43c9-8862-0f1007068669">
<img width="793" alt="zoom m4 start" src="https://github.com/ncstate-delta/moodle-mod_zoom/assets/14754240/1fbed49e-b298-419a-b200-9ebfe1a6bf4e">
