### ISSUE TITLE
Alternative user identifier field is not work when creating an activity/meeting

### ISSUE THREAD

**Issue by JcpPY** [jrchamp/moodle-mod_zoom#501]
Hello, I am testing this version in Moodle version 4.1+ (Build: 20221222) (2022112800.05) with Oauth server to server and when placing the credentials and save, I get the error:
Connection status: Connection failed: HTTP Status 403
I tried the credentials via postman and I got an ok response.

Thank You in advance and regards.

Juan Carlos

**Comment by jrchamp** [comment]
Hi @JcpPY,

I'm not sure why it's not working for you. Those errors message are from Moodle itself and should not be possible. You may want to report an issue to Moodle, because that line should not be reachable: https://github.com/moodle/moodle/blob/a1d5d1b2f758a3178bff4c42883a477f4b1ea50c/lib/mustache/src/Mustache/Loader/FilesystemLoader.php#L133

Moodle specifically overrides that method because they never initialize the baseDir class variable: https://github.com/moodle/moodle/blob/a1d5d1b2f758a3178bff4c42883a477f4b1ea50c/lib/classes/output/mustache_filesystem_loader.php#L66

As far as the issue you are experiencing, please make sure you have granted the required scopes to the Server-to-Server OAuth app.

**Comment by jrchamp** [comment]
Also, please make sure you are using Moodle 4.1.2 or newer if you are using PHP 8.1.

**Comment by JcpPY** [comment]
Hi Jonathan
Thanks for your answer.
Let's switch to PHP 7.4 and see how it goes

**Comment by JcpPY** [comment]
PHP 7.4 installed, but same thing:
Connection status: Connection failed: HTTP Status 403
Changing Zoom API Identifier from email address to username we have this status
Connection status: Connection working
But in this case we get this message when trying to create rooms
Unable to find your account on Zoom. If you are using Zoom for the first time, you must activate your Zoom account by logging into https zoom us. Once you've activated your Zoom account, reload this page and continue setting up your meeting. Else make sure your email on Zoom matches your email on this system
In moodle we would only have to see this:
admin/environment/phpextension/soap
It is the only warning that we have as a recommendation

**Comment by jrchamp** [comment]
It sounds like you are saying:

 - In Moodle, the user's email address is jon_champ@example.com, and username is jrchamp@example.com
 - In Zoom, the username is jrchamp@example.com
 - So mod_zoom, you have changed the identifier field from `email` to `username` and it's working on the Connection test, but it's not working when trying to add an instance of the mod_zoom activity (specifically, creating a new Meeting).

Is that correct?

**Comment by JcpPY** [comment]
Hi, yes, that is correct

**Comment by JcpPY** [comment]
Hello Jonathan
We are not able to use the plugin yet. we tried the latest version, same error. For testing purposes we installed local versions of the latest Moodle version and same result. Is it possible that you could take a look at our case?
Regards

**Comment by jrchamp** [comment]
Sorry @JcpPY, I have this on my list to look at. This week is not possible, but hopefully the week after.

**Comment by jrchamp** [comment]
Hi @JcpPY - I have tried everything I can to reproduce the error you reported. I have tried setting the Zoom API identifier to username, idnumber and email. It works every time for me. If possible, can you try using the Zoom user identifier (it's a bunch of random letters that shows up in links from the User Management -> Users list) to see if that works?
