### ISSUE TITLE
Exception caused on settings page

### ISSUE THREAD

**Issue by jwalits** [jrchamp/moodle-mod_zoom#502]
![2023-07-28_16-10](https://github.com/ncstate-delta/moodle-mod_zoom/assets/56375964/a22a8ddb-f64f-4939-bd70-7b44432d995f)

We are recently seeing this error on the settings page caused by: https://github.com/ncstate-delta/moodle-mod_zoom/blob/main/settings.php#L51

In most cases this line is fine as $errormessage is a string, but in some cases `$error->a` is not a string.

Like in our case where API gets rate limited and an error is thrown after retries, $a is not a string but an object : https://github.com/ncstate-delta/moodle-mod_zoom/blob/main/classes/webservice.php#L271 - https://github.com/ncstate-delta/moodle-mod_zoom/blob/main/locallib.php#L146-L156

This causes the whole settings page to be broken. This ideally should be handled gracefully.

We are running this on Moodle: 3.9.22+, with PHP: 7.4 and MySQL database version 8.0

**Comment by jrchamp** [comment]
Hi @jwalits,

Please take a look at #503 so see if that resolves the issue you are experiencing.

**Comment by jwalits** [comment]
Thanks for the quick response @jrchamp - we will test it out and get back to you
