### ISSUE TITLE
modifiying a existing meeting with a title over 200 car shows an unsignificant error

### ISSUE THREAD

**Issue by lcollong** [jrchamp/moodle-mod_zoom#511]
Hi,

The meeting/patch api entry says that "topic" field is limited to 200 car. So when you try to modify an existing meeting changing its title so that this limit is overshooted (french could be long text !), it shows an error message hard to understand : "Impossible de modifier Zoom" ("impossible to modify zoom").

Whereas the actual response from the api contains more useful info :
"response": {
"code": 300,
"message": "Validation Failed.",
"errors": [
{
"field": "topic",
"message": "Invalid field."
}
]
}

It would be nice to show up the "Validation Failed" response-->message content as an extra text to the standard generic "not able to" which would allow the user or the support team to find the origin of the problem faster.

**Comment by smbader** [comment]
I think the simple solution is to reduce the title length validation down to match Zoom's limits. This will provide a useful validation error to the user.

https://github.com/ncstate-delta/moodle-mod_zoom/blob/124e439f1edb5d6c32dbb0d9840934d60d95c94d/mod_form.php#L171C1-L172C1

**Comment by lcollong** [comment]
Well done. Thanks.
