### ISSUE TITLE
Session report does not synchronise

### ISSUE THREAD

**Issue by xmontana** [jrchamp/moodle-mod_zoom#513]
Hello,

We have installed version v5.0.0 (2023070300) on Moodle 3.9, everything works correctly  (sessions, video records...) but the session report does not appear in the Zoom activity.

The APP in Zoom is created as Server-to-Server OAuth inside the package administrator account, and has all the documented permissions.

The cron task executes but doesn't find any meeting, and we have try to force with the reports by cli:

```
php get_meeting_report.php --start=2023-8-20 --end=2023-8-31
Finding meetings between 2023-8-20 to 2023-8-31
Using Dashboard API
Processing 0 meetings
DONE!
```

**Comment by jrchamp** [comment]
First, is there any chance that 2023-08-20 and 2023-08-31 fixes the issue? I know that the get_meeting_reports task needs an OAuth-era refresh, but I'm hoping it's not quite this broken...

**Comment by jrchamp** [comment]
I have opened an initial pull request in #514 to try and address some of the issues. Please take a look and see if it helps.

**Comment by xmontana** [comment]
Thank you for your help @jrchamp  

I have try both date formats (2023-8-20 and 2023-08-20). Then I try again with your PR #514 upgrading the plugin to v5.1.0 2023082400 with the 2 files changes, and try again with the same result, 0 meetings and reports.

**Comment by jrchamp** [comment]
Hi @xmontana, PR #525 has been merged into the `main` branch as we prepare for a release. I'm hoping it fixes the issue for you. Another thing that may help: Although the `report:read:admin` permission is optional when using the Dashboard data, I think the Report data may be more consistent. If either of these fixes the issue, please let us know.

**Comment by xmontana** [comment]
Thank you so much @jrchamp ,

After testing your PR, we could see that we had a problem with the group permissions in the scope of the Zoom marketplace APP. 

Now we have it all working! 🎉
