### ISSUE TITLE
Zoom Meeting Activity added, says hidden to some Students 

### ISSUE THREAD

**Issue by ejohnlove** [jrchamp/moodle-mod_zoom#520]
Hi,

One of our instructors has created a Zoom Meeting activity that most of his students can see/access, but a few students cannot.
There are no groups or group settings set, and I cannot see any reason for the added activity to not show up in the course for a few students only.

(We're running Moodle 4.1, and 5.1.0 of Zoom Meeting.)

Do you have any recommendations?

**Comment by ejohnlove** [comment]
Never mind. The affected Students had no roles in the course (as in blank where "Student" role should be). This is not a bug in the Zoom Meeting activity at all. Apologies.

**Comment by jrchamp** [comment]
No worries! Glad you were able to find the problem and get it addressed.
