### ISSUE TITLE
Allow Recurring meetings to have state of 'No fixed date'

### ISSUE THREAD

**Issue by easegill** [jrchamp/moodle-mod_zoom#523]
There is a setting in the plugin (zoom | defaultrecurring) which allows new meetings to default to be recurring. This used to give meetings that had no fixed time i.e. they didn't recur at specific times each day, week, etc. It appears that a change at the Zoom end means that that new meetings with a default of 'recurring' are now created to recur 'Daily'. Can an additional option be added to allow the default recurrence interval to also be set?

![Zoom Recurrence](https://github.com/ncstate-delta/moodle-mod_zoom/assets/1159301/0fdcd319-37c3-4bf9-8a9d-0f8797a3931c)

**Comment by jrchamp** [comment]
Thank you @easegill for opening this issue!

Implementers: While it is still possible to select "No Fixed Time" for the Recurrence Type, it is no longer the default when the `defaultrecurring` option is active. That is a regression that was likely introduced by #189
