### ISSUE TITLE
invalid calls to mod_zoom_external 

### ISSUE THREAD

**Issue by danmarsden** [jrchamp/moodle-mod_zoom#527]
c522487652eb4087b12d07a9b5070a9edfeeb819 renamed mod_zoom_external to mod_zoom\external

but... events.php still refers to mod_zoom_external, and so does classes/output/mobile.php

**Comment by danmarsden** [comment]
this triggers the following unit test failures:

There were 2 errors:

1) core\externallib_test::test_all_external_info with data set "mod_zoom_get_state" (stdClass Object (...))
coding_exception: Coding error detected, it must be fixed by a programmer: Cannot find external class mod_zoom_external

/var/www/html/lib/externallib.php:93
/var/www/html/lib/tests/externallib_test.php:442
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97

2) core\externallib_test::test_all_external_info with data set "mod_zoom_grade_item_update" (stdClass Object (...))
coding_exception: Coding error detected, it must be fixed by a programmer: Cannot find external class mod_zoom_external

/var/www/html/lib/externallib.php:93
/var/www/html/lib/tests/externallib_test.php:442
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97

**Comment by jrchamp** [comment]
Thanks @danmarsden! Really glad you caught this before we released and tagged a new version.
