### ISSUE TITLE
Meeting with no set time

### ISSUE THREAD

**Issue by Melle-Amu** [jrchamp/moodle-mod_zoom#528]
Hi
When you create a permanent meeting (with no set time), a description under the activity indicates the meeting start time. This time is incorrect and should not appear (it's a meeting with no set time). Is this a bug?
Thank you ! 

![moodle](https://github.com/ncstate-delta/moodle-mod_zoom/assets/146946656/d8b3f58f-7619-44ce-9efb-c492acbf2585)
![moodle2](https://github.com/ncstate-delta/moodle-mod_zoom/assets/146946656/e6a86ac7-c59d-4fa2-9910-dc9e4413a8db)

**Comment by smbader** [comment]
Introduced in this commit: 
https://github.com/ncstate-delta/moodle-mod_zoom/commit/e301e2df1cc912eef427fa77db39838228854e86

The recommended fix is to not display a start time when "no fixed time" is selected.
