### ISSUE TITLE
Zoom activity is visually zoomed, when hovering with the cursor

### ISSUE THREAD

**Issue by mwreichel** [jrchamp/moodle-mod_zoom#533]
Hi,

another bug we found with theme "boost" (another themes) in 4.2 and 4.1 is concerned with hovering over Zoom activities in a course.
When you do that, the activity is "zoomed" (-> please see attached video).
This doesn't follow the usual behaviour of activites or resources in Moodle.

[zoom_screencast2.webm](https://github.com/ncstate-delta/moodle-mod_zoom/assets/16242126/fdfea83d-3cff-441a-a8c8-a0a7d5538edf)

We would appreciate a solution for that.

Thanks in advance,
Martin

**Comment by jrchamp** [comment]
Thank you @mwreichel for reporting this issue. I was unable to replicate the shown behavior in an unmodified version of Moodle and was unable to find any code within our plugin that would cause the behavior.

The ".zoom:hover" behavior appears to be coming from the Wunderbyte Table plugin: https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/blob/fdbe33d59601f3bf9b4453115b0d5684fa628a0f/styles.css#L297-L300

**Comment by mwreichel** [comment]
Thanks for you quick answer to my comment.
You might be right, we use this plugin too. I will check it tomorrow on one of our instances.

**Comment by bernhard-wunderbyte** [comment]
We fixed this in Wunderbyte Table 1.8.0: https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/releases/tag/v1.8.0
