### ISSUE TITLE
The connector has stopped working.

### ISSUE THREAD

**Issue by Atlassrl** [jrchamp/moodle-mod_zoom#538]
Good morning, I followed all the instructions to be able to switch to the S2S version of zoom meeting, the plugin worked correctly for a few days and then stopped working. It can no longer connect. I tried to recreate a new app on zoom and configure the keys but on moodle this error appears in the plugin configuration page: (Connection status: Connection failed).
I also checked the permissions of the S2S account owner. This is not a temporary Zoom outage as it has persisted for more than a week. We have a paid version of Zoom.
  Why did it stop working? Could there be a server-side crash?
Could any specialist help me?

**Comment by jrchamp** [comment]
Thanks @Atlassrl for reaching out. Which version of the mod_zoom plugin are you using?

**Comment by Atlassrl** [comment]
v5.1.0

**Comment by jrchamp** [comment]
@Atlassrl I'm looking at the the code that shows "Connection status: Connection failed", specifically:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/802df30e4d9af2babfdac361d3a6575950a4a1b2/settings.php#L39-L55

zoom_get_user() calls the webservice's get_user() method:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/802df30e4d9af2babfdac361d3a6575950a4a1b2/locallib.php#L1282

To get the "Connection failed" message, an Exception or Error needs to be thrown that is not "user not found". If we found the user, or we successfully confirmed that the user does not exist, we know that the connection is working.
https://github.com/ncstate-delta/moodle-mod_zoom/blob/802df30e4d9af2babfdac361d3a6575950a4a1b2/classes/webservice.php#L512-L522

So what we really need to know is which Throwable is actually being thrown and why. If the exception is a `\mod_zoom\webservice_exception` or one of its children, then there should be more text after the Connection failed message. There isn't more text, so it might be a moodle_exception that doesn't have an `a` member variable.

Summary: If I'm correct that it is a `moodle_exception`, then please try modifying the following line:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/802df30e4d9af2babfdac361d3a6575950a4a1b2/settings.php#L49
To have this code instead:
```php
            $errormessage = $error->getMessage();
```

**Comment by Atlassrl** [comment]
I modified the line into  $errormessage = $error->getMessage(); and I see the following error:

**Comment by jrchamp** [comment]
Hi @Atlassrl,

I searched everywhere and could not find where that specific string might be coming from. Here's some additional debugging information that will hopefully help:
```php
    $errormessage = $error->getMessage() . PHP_EOL;
    $errormessage .= 'Thrown from ' . $error->getFile() . '(' . $error->getLine() . ')' . PHP_EOL;
    $errormessage .= $error->getTraceAsString() . PHP_EOL;
```

**Comment by jrchamp** [comment]
Okay, so line 1135 is when we're trying to get a fresh OAuth token and we're making sure that the response from the Zoom OAuth endpoint has returned successfully.
https://github.com/ncstate-delta/moodle-mod_zoom/blob/d4db341b3429c6f3cbd82a3454d852423b7b2d3d/classes/webservice.php#L1134-L1136

For some reason, in your situation, the curl object's "error number" value is not empty, but the "error string" is empty.

So let's check what the errno value is by modifying line 1135 as follows:
```php
        if ($curl->get_errno()) {
            throw new moodle_exception('errorwebservice', 'mod_zoom', '', $curl->get_errno() . ' - ' . $curl->error);
        }
```

**Comment by Atlassrl** [comment]
@jrchamp here's the error:  "Connection status: Connection failed:An error occurred in the Zoom webservice: 77 - "

**Comment by jrchamp** [comment]
@Atlassrl cURL error 77 indicates there's a problem with your locally installed Certificate Authority files.

If you run `curl -v -I https://zoom.us/`, there should be some information about which CAfile and CApath is in use. If it fails, it will probably say "error setting certificate file:" followed by the CAfile it is trying to use. The CApath should be world readable and world executable, while the CAfile should be world readable (there's no secrets in these files and they are necessary for programs to be able to verify remote systems). Depending on which operating system you are using, you may want to try updating or reinstalling the CA certificates package (ca-certificates on many common Linux distributions).

Please let us know if that resolves the issue!

**Comment by Atlassrl** [comment]
@jrchamp it works now! Thank you for all you've done.
