### ISSUE TITLE
Since v5.1.1, error with PHP 8.0 : "in_array(): Argument #2 ($haystack) must be of type array, null given"

### ISSUE THREAD

**Issue by foxlapinou** [jrchamp/moodle-mod_zoom#541]
Hi,

I use Zoom plugin on several Moodle platforms, since several years, with no problem.

Since i upgraded from 5.1.0 to 5.1.1, i have errors in cron execution of task mod_zoom\task\get_meeting_reports :

Scheduled task failed: Obtenir un rapport des réunions de Zoom. (mod_zoom\task\get_meeting_reports),in_array(): Argument #2 ($haystack) must be of type array, null given

I have this problem with Moodle 4.1 on RedHat 8, with PHP 8.0.30 and MariaDB 10.6.15. No problem with Moodle 4.0 on RockyLinux, with PHP 7.3.33.

I think it's something related to some code introduced by 5.1.1 (compared to 5.1.0), not fully compatible with PHP 8.0.

Séverin

**Comment by smbader** [comment]
Hello Séverin,

We think we may have spotted this issue. Thank you for reporting this.  

Steve
