### ISSUE TITLE
Differentiate between recorded versions of the same meeting?

### ISSUE THREAD

**Issue by segevr** [jrchamp/moodle-mod_zoom#547]
Hi,

We've started using the record management functionality of this plugin and I noticed that there's no way to know which "version" of the meeting each link is for.
Stuff like "speaker view", "gallery view", etc...
We have around 5-6 versions of each meeting recorded, and in our Moodle all the links show up with the same text:

![image](https://github.com/ncstate-delta/moodle-mod_zoom/assets/47896150/34918b80-4f3f-45c0-9ce9-024ade13acc7)

Can you guys add the option to show the version name instead of the "(Video and Audio)" part?
So for example we'll have those 5-6 links like before, but each will have a descriptor at the end like "(Speaker view with shared screen)" etc.
(If possible, please have those as translatable strings)

Would be even better if we could decide system-wide (or even for each Zoom module) which versions we want to show, but I'm sure that'd be a lot more complicated :)

Thanks!

**Comment by jrchamp** [comment]
Thanks @welegionsr, this is a great suggestion! We've marked it as a bug, because there are multiple links which are labeled identically but have different destinations (an accessibility problem).

Testing steps for developer:

1. Check every Cloud Recording checkbox option.
2. Create a test recording.
3. Check the API response to identify possible data elements to differentiate between versions/formats of the recordings.

**Comment by jrchamp** [comment]
@cbounphengsy If you need any help on this one, I'd be happy to step through this with you.

**Comment by jrchamp** [comment]
Looks like there is a `recording_type` value for each file: [List all recordings](https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/recordingsList)

We may want to add translatable strings for each of these language string keys:
```
recordingtype_shared_screen_with_speaker_view(CC)
recordingtype_shared_screen_with_speaker_view
recordingtype_shared_screen_with_gallery_view
recordingtype_speaker_view
recordingtype_gallery_view
recordingtype_shared_screen
recordingtype_audio_only
recordingtype_audio_transcript
recordingtype_chat_file
recordingtype_active_speaker
recordingtype_poll
recordingtype_timeline
recordingtype_closed_caption
recordingtype_audio_interpretation
recordingtype_summary
recordingtype_summary_next_steps
recordingtype_summary_smart_chapters
recordingtype_sign_interpretation
recordingtype_production_studio
```
That would allow the PHP to display the recording type string using something like:
```php
get_string('recordingtype_' . $recording['recording_type'], 'mod_zoom');
```

**Comment by jrchamp** [comment]
Some of the types above are JSON or may contain user-data (specifically, the poll CSV file). Probably doesn't make sense to include them.

Looks like we are already filtering the file_type to MP4/M4A, so we won't have JSON/CSV.
https://github.com/ncstate-delta/moodle-mod_zoom/blob/b3a1e3a6a5f4d84c20bf0a9ef4e61219b35545a2/classes/webservice.php#L1039-L1044

The current list of file types:
`MP4┃M4A┃CHAT┃TRANSCRIPT┃CSV┃TB┃CC┃CHAT_MESSAGE┃SUMMARY`

We may want to add the TRANSCRIPT (vtt), CHAT (text), CC (vtt) files to the hardcoded list. If we wanted to go the extra mile, we could make it a configuration option (probably admin-level).
