### ISSUE TITLE
in Breakout rooms setting, allow to show Human names

### ISSUE THREAD

**Issue by mofetdanielsmolkin** [jrchamp/moodle-mod_zoom#551]
hello, 

is it possible to see Human readable names with emails or just human names in breakout rooms feature? 

![image](https://github.com/ncstate-delta/moodle-mod_zoom/assets/78465711/e21581b4-0b75-4575-b24b-25243f3e0f89)

thanks in advance :)

**Comment by jrchamp** [comment]
What do you see right now? I'm not sure what part of the screenshot I should be focusing on.

**Comment by mofetdanielsmolkin** [comment]
inside the dropdowns  you have list of emails (users),
 is it possible to show student's full name instead of emails or as an addition to the email?
