### ISSUE TITLE
add option to hide start-information when using reoccurring meeting

### ISSUE THREAD

**Issue by jarvil1** [jrchamp/moodle-mod_zoom#559]
Hello,

I would like to see an feature that lets you hide start-information when you are using reoccurring meeting.

![image](https://github.com/ncstate-delta/moodle-mod_zoom/assets/53904029/84141d08-a151-4627-8cb9-f0f3d9c0af71)

![image](https://github.com/ncstate-delta/moodle-mod_zoom/assets/53904029/9f73c0dc-c0be-4e1f-99fe-9beb79745a43)

**Comment by smbader** [comment]
Hi Jari,

This was fixed in [v5.1.1](https://github.com/ncstate-delta/moodle-mod_zoom/releases/tag/v5.1.1), though we recommend using the latest version which includes other bug fixes.

What Zoom version are you currently using?

Thank you!

**Comment by Urpokarhu1** [comment]
Hello,
We are using 5.10 but need to try the update then.
