### ISSUE TITLE
Class "mod_zoom\context_module" not found error on Moodle Mobile

### ISSUE THREAD

**Issue by derbear444** [jrchamp/moodle-mod_zoom#566]
Hello!

We are seeing the following error on Moodle Mobile when trying to open a Zoom meeting in a course:
![mobile-error](https://github.com/ncstate-delta/moodle-mod_zoom/assets/77299230/a94506b5-2d85-451e-a106-f097a83c5b56)

Additional information:

- PHP: 8.1
- Moodle: 4.1.6+
- mod_zoom: v5.1.0 (2023082400)

I saw that this issue was already reported on the Moodle plugins directory site, but wanted to create a ticket we could follow so we know when it is patched.

Thanks!

**Comment by jrchamp** [comment]
For now, I'm going to close this issue as resolved by #554. Please reopen if the issue persists in v5.1.4 or newer.
