### ISSUE TITLE
Large icon on sessions export page

### ISSUE THREAD

**Issue by haietza** [jrchamp/moodle-mod_zoom#579]
When you access the participants page from a Zoom activity sessions report (mod/zoom/participants.php), the Excel icon is very large (see attached screenshot). It looks like previous icons in Moodle were smaller images, so no sizing needed to be done?

Occurs in Moodle 4.3.3 (Build: 20240212)and version v5.1.5 2024012500 of the Zoom plugin, on both Boost and Classic themes.

Thank you!
![icon](https://github.com/ncstate-delta/moodle-mod_zoom/assets/669666/81b78c9c-8db0-49db-893f-3aa116cb2ff8)

**Comment by jrchamp** [comment]
Thanks @haietza! We'll take a look at this. If you figure it out before we do, please let us know. 😁

**Comment by haietza** [comment]
@jrchamp I just put in a pull request, should be a small fix. Thanks!
