### ISSUE TITLE
The settings section appear to mix action when expanding and collapsing

### ISSUE THREAD

**Issue by kiratskitizing** [jrchamp/moodle-mod_zoom#582]
SEQUENCE TESTING
First visit/loading, the following sections appear as:
Expanded: General, Schedule, Breakout rooms, Security, Media, Host
Collapsed: Grade, Groups and visibility, Restrict access, tags.

Testing: Click the General section (currently Expanded)
RESULT: 
Expanded: Breakout rooms
Collapsed: General, Schedule, Security, Media, Host, Grade, Groups and visibility, Restrict access, Tags

Testing: Click the General section (currently Collapsed)
RESULT:
Expanded: General, Schedule, Breakout rooms, Security, Media, Host
Collapsed: Grade, Groups and visibility, Restrict access, tags.

Testing: Click the Media section (currently Expanded)
RESULT:
Expanded: Breakout rooms
Collapsed: General, Schedule, Security, Media, Host, Grade, Groups and visibility, Restrict access, Tags

Per above, it appears there is a mixed of sections that is attached to other section and the action appears to be confusing due to the results of expansion and collapsing of the sections.

I am not sure if this is somewhat related to https://github.com/ncstate-delta/moodle-mod_zoom/issues/380

**Comment by jrchamp** [comment]
Thanks @kiratskitizing! It looks like this "behavior" was first introduced in #201. It's not exactly a regression, but it should definitely be fixed. For each of the `header` elements, the second parameter is used for the HTML `id`. We should use something unique. Also, similar to the Breakout Rooms, we should decide if the section is expanded by default or not.

**Comment by armccoy** [comment]
In my testing, after making the header IDs unique, the only sections expanded on first visit/loading are _General_ and _Breakout Rooms_. For consistency and UX sake, I think it might be best to make sure the previously expanded sections are retained:

_General, Schedule, Breakout rooms, Security, Media, Host_

Let me know if this sounds good.
