### ISSUE TITLE
New scopes by ZOOM / Plugin not work!

### ISSUE THREAD

**Issue by amendezinserver** [jrchamp/moodle-mod_zoom#583]
In relation to the changes introduced in the Moodle <> Zoom integration using OAuth described on the Zoom website (https://developers.zoom.us/docs/integrations/oauth-scopes-overview) it is not possible to use the Zoom plugin .

With the latest version (5.2.0) I get the following errors:

Connection status: Connection failed:The Zoom OAuth configuration is missing these required scopes: meeting:read:admin, meeting:write:admin, user:read:admin

Anyone else with this problem?
Do you know which scopes are the ones that need to be declared?
Is a new version of the ZOOM plugin necessary?

Thank you very much in advance!

**Comment by jrchamp** [comment]
Thanks @amendezinserver! I just saw that Zoom had changed the OAuth scopes for newly created integrations, and yes, if people are unable to use the Legacy OAuth scopes, then we will need to - quickly - update the plugin to:

1. Document the new set of required and optional scopes when an integration is using the newly created Granular Scopes.
2. Modify the code to check for either the Granular Scope or the Legacy Scope when checking permissions.

Questions that need to be answered:

1. What are the new Granular Scope equivalents for the functionality we offer? 
2. Is it possible to upgrade an existing integration from Legacy Scopes to Granular Scopes?
3. Is it possible to create new integrations that use Legacy Scopes?

Based on what I read, it seems like both 2 and 3 are "No".

**Comment by jport500** [comment]
Happy to help test the fix.

**Comment by amendezinserver** [comment]
Thank you very much!

**Comment by jrchamp** [comment]
@amendezinserver @jport500 @haietza

v5.2.1 has been released which should address most of the granular scopes problems. Zoom does not yet have granular scope support for Tracking Fields, but everything else should work. If you run into any problems, please open a new GitHub issue so we can have a focused place for each problem.
