### ISSUE TITLE
provide meaningful HTML ids for the details of the activity

### ISSUE THREAD

**Issue by a-kempka** [jrchamp/moodle-mod_zoom#597]
Thanks for the great plugin.

It would be very useful if the HTML-page for the meeting details contained ids that I could reference with JavaScript or CSS. There are some examples where we need to modify the page containing the button to enter the meeting dynamically based on specific needs of the teachers

* we want to force the students to enter the meeting via the button so that the activity can complete and unlock other activities in the course. clicking the URL of the meeting does not trigger the activity completion.
* sometimes it is necessary to display the meeting details to students when the button fails to open the meeting and the meeting details have to be entered manually in the zoom app.

For those cases having ids in the HTML (for the tables and the specific rows) would be very helpful
* ids for each section (h3 and the table below) - or adding a div containing the h3 and the subsequent table
* ids for each row of the table (meeting id, link, code, time, etc.)

**Comment by smbader** [comment]
Thank you Andreas!

This page could certainly use a little attention. For the left column of the table, we may also want to use "th" and I can see how ids, classes, and names here could be a very helpful improvement.

Steve

**Comment by jrchamp** [comment]
> * clicking the URL of the meeting does not trigger the activity completion.

As a workaround, please try turning off the "Security" section's visibility. It's a setting at both the admin and activity level.

**Comment by a-kempka** [comment]
@jrchamp - we considered hiding the security section's visibility, however we have a specific, but (I think) generally useful use case:

We want to hide the detail information for the meeting in order to force students to click the "join meeting" button as this will trigger an activity completion and enable another activity (a quiz or lti link) in the course. showing the meeting details, especially the meeting link, distracts some of the students and they ignore the button.
There are some cases in which the button does not help, e.g. when the browser is set up in a wrong way preventing proper zoom meetings (links don't open, the browser is not allowed to use the camera). Then students should be able to see the meeting details.

Our workaround currently is to use JavaScript in the description of the zoom activity that hides the security table but only shows it when a link is clicked ("help me, I can't start the meeting"). The JavaScript now depends on the contents of the table and thus depends on the language chosen. It would be way easier to have proper ids for every table, row and cell to be indepentent of the language chosen.
