### ISSUE TITLE
Zoom meeting - What happens after changing the URL of the Moodle server?

### ISSUE THREAD

**Issue by Pig-ment** [jrchamp/moodle-mod_zoom#600]
Hi,
We move to a new Moodle server each year. For example, soon our current Moodle server that now uses the following URL:
https://moodleserver.edu/
will change its URL to the following one:
https://moodleserver2024.edu/
and a new Moodle server will use the https://moodleserver.edu/ URL, since then it will be the current Moodle server.

I worry now that the change of URLs, depending on how your Zoom integration via the plugin works, could lead to a situation that the data the Zoom plugin pulls from Zoom server could be disrupted. If the current server has a Zoom meeting activity in a course which its course ID is  2, and after going live with the new server which would have the exact same URL, there would be a Zoom activity in a course which its course ID is 2, what would happen with the data? If the Zoom plugin tries to match the data from Zoom server back to Moodle based on the URL of the server and the course ID, that could create confusion.

And even if the data is not matched based on the server URL and course ID, but on the server URL and the activity ID, I assume there could also be duplicates of the activity ID in both servers (the new https://moodleserver.edu/ server and the https://moodleserver2024.edu/ which once had the https://moodleserver.edu/ URL).

We would really be happy if the plugin creators could clarify this issue and explain how the matching of data from Zoom server to the Zoom meeting plugin activities.

Thanks a lot 🙂

**Comment by jrchamp** [comment]
Hi @Pig-ment,

It's so nice to see other organizations that are using the annual Moodle server model! There should not be any issues for the Zoom activity plugin when changing the Moodle server's URL. When the Zoom plugin matches data using Zoom's API, it uses Zoom's identifiers, not the Moodle activity identifiers (for example, the Zoom meeting ID or the Zoom meeting UUID).

If you have additional questions about this, please let us know! ❤
