### ISSUE TITLE
Moodle display filters for zoom meeting topics and description

### ISSUE THREAD

**Issue by behanw** [jrchamp/moodle-mod_zoom#610]
Although I understand that zoom topics and descriptions don't take html, they are populated by data entered into zoom activities which are processed through Moodle filters when viewed through Moodle. These filters can introduce html, but some filters (like [filterCodes](https://moodle.org/plugins/filter_filtercodes) and [Generico](https://moodle.org/plugins/filter_generico)) can also be used to template dynamic text, or template common, or variable output depending on context.

For instance, {coursename} is automatically expanded to the full name of the current course, which can be very handy when naming Zooms without having to adde the course name manually.

Similarly, if you want to include dynamic text to be shown when on mobile or not you can use {ifmobile}{/ifmobile} or {ifnotmobile}{/ifnotmobile} to wrap text to be rendered appropriately.

It is also very convenient to template common blocks of text using generico so you can maintain how something is worded globally instead of having to update the same text individually in every course and/or activity in which it is used.

At the moment these shortcodes all show up in zoom topics and descriptions in zoom (without being expanded by the appropriate Moodle filters), despite being rendered properly when viewed in Moodle in the Zoom Activity.

You can learn more about available Moodle filters here: https://docs.moodle.org/404/en/Filters

It appears one can use format=FORMAT_PLAIN when using filters to output filtered text without introducing html to the processed string using the filter api.

https://moodledev.io/docs/4.4/apis/subsystems/output#string-formatting-functions

Specifically it appears that format_string() can be used to preprocess strings before they are set to the topic and description in Zoom (outside of Moodle).

https://moodledev.io/docs/4.4/apis/subsystems/output#format_string

**Comment by jrchamp** [comment]
Test case:

- Activity title `{courseshortname} Meeting 1`
- Activity intro text `First Zoom meeting for {coursename}`
- Expected: "MyCourse Meeting 1" and "First Zoom meeting for My Awesome Course"
