### ISSUE TITLE
Wrong duration

### ISSUE THREAD

**Issue by sam-suresh** [jrchamp/moodle-mod_zoom#613]
![image](https://github.com/user-attachments/assets/afd3b04f-96df-42ad-b70f-239600ed7a17)

The last call for example, took 4 minutes but it shows 4 seconds. 
v5.2.3 (2024072500)

**Comment by jrchamp** [comment]
Hi @sam-suresh,

It looks like you have the updated version of the code, but the upgrade task may not have run. Specifically:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/aa8208402f29574cbecd8de594ce520646c5ec36/db/upgrade.php#L980-L991

Do you know if a Moodle admin has gone through the upgrade steps? If you log in as an admin, or specifically go to `/admin/index.php`, it should have indicated that an upgrade was necessary.

If Moodle thinks that everything is upgraded, the SQL to fix all of the rows at once looks like:
```sql
UPDATE mdl_zoom_meeting_details SET duration = end_time - start_time;
```

If you have any questions, please let us know.

**Comment by jrchamp** [comment]
Closing for now as this should be fixed by the upgrade step. If you are still experience this issue, please reopen and provide additional details.
